### ISSUE TITLE
Scala 2.13 Class de.fau.cs.osr.ptk.common.ast.AstNode not found - continuing with a stub.

### ISSUE THREAD

**Issue by intracer** [scala/bug#11664]
Repository to reproduce https://github.com/intracer/scala-sweble-bug

https://travis-ci.org/intracer/scala-sweble-bug/builds/568019084

Builds with 2.11 and 2.12 success, 2.13 fails compilation with message

[error] Unable to locate class corresponding to inner class entry for AstInnerNode2 in owner de.fau.cs.osr.ptk.common.ast.AstAbstractInnerNode
[error] /home/travis/build/intracer/scala-sweble-bug/src/main/scala/SwebleParser.scala:19:24: Class de.fau.cs.osr.ptk.common.ast.AstNode not found - continuing with a stub.

**Comment by SethTisue** [comment]
looks like a missing transitive dependency. where is the `de.fau.cs.osr.ptk.common.ast.AstNode` class supposed to come from?

**Comment by SethTisue** [comment]
(scalac is not necessarily principled about requiring or not requiring a transitive dependency to be present on the classpath, as discussed at https://github.com/scalacenter/advisoryboard/blob/master/proposals/009-improve-direct-dependency-experience.md)

**Comment by intracer** [comment]
it is in https://mvnrepository.com/artifact/de.fau.cs.osr.ptk/ptk-common/3.0.8 which is included by sbt
I just copied all the required jars and ran scalac directly and got the same error
scalac SwebleParser.scala -classpath "*.jar"                                                                                                                   error: Unable to locate class corresponding to inner class entry for AstInnerNode2 in owner de.fau.cs.osr.ptk.common.ast.AstAbstractInnerNode                                                           SwebleParser.scala:19: error: Class de.fau.cs.osr.ptk.common.ast.AstNode not found - continuing with a stub.                                                                                                parsePage("title", "text")                                                                                                                                                                                                 ^                                                                                                                                                                                two errors found

**Comment by SethTisue** [comment]
interesting. @lrytz what do you make of this? the transitive dependency is on the classpath

**Comment by lrytz** [comment]
This regressed in 2.12.7, caused by https://github.com/scala/scala/pull/7147. @retronym can I leave it to you?

**Comment by retronym** [comment]
Some JAR(s) on the classpath contains entries like:

```
org/sweble/wikitext/engine/ExpansionCallback.class
org.sweble.wikitext/swc-engine/git.properties
```

This confuses the new indexing scheme we have for Zip metadata that assumed that it could index `a/b/c` by `a.b.c` to optimize lookups. I'll find a way to fix it ASAP.
