### ISSUE TITLE
Cannot extend JavaFX class DatePickerSkin

### ISSUE THREAD

**Issue by countfloyd** [scala/bug#11584]
Attaching a tar file of sample project. Simple run 'sbt compile' to see the error. I don't see any workaround for this problem.

Code works in 2.12.8 but not 2.13.0

[bug.zip](https://github.com/scala/bug/files/3321722/bug.zip)

Error is:

```
[error] /Users/curtis/guild1/code/bug/src/main/scala/Bug.scala:4:7: incompatible type in overriding
[error] private[package skin] def getBehavior(): com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior[_] (defined in class ComboBoxBaseSkin)
[error]   with private[package skin] def getBehavior(): com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (defined in class DatePickerSkin);
[error]  found   : ()com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior
[error]  required: ()com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior[_]
[error] class Bug(ymPicker: DatePicker) extends DatePickerSkin(ymPicker) {
[error]       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

**Comment by hrhino** [comment]
Two raw types were walking down the street. One was cooked, the other wasn't?

```
[nix-shell:~]$ export CP=/home/haro/.ivy2/cache/org.openjfx/javafx-base/jars/javafx-base-12.0.1-linux.jar:/home/haro/.ivy2/cache/org.openjfx/javafx-graphics/jars/javafx-graphics-12.0.1-linux.jar:/home/haro/.ivy2/cache/org.openjfx/javafx-controls/jars/javafx-controls-12.0.1-linux.jar:/home/haro/.ivy2/cache/org.openjfx/javafx-fxml/jars/javafx-fxml-12.0.1-linux.jar

[nix-shell:~]$ javap -cp $CP -s javafx.scene.control.skin.DatePickerSkin | grep -C 1 getBehavior

  com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior getBehavior();
    descriptor: ()Lcom/sun/javafx/scene/control/behavior/ComboBoxBaseBehavior;

[nix-shell:~]$ javap -cp $CP -s javafx.scene.control.skin.ComboBoxBaseSkin | grep -C 1 getBehavior

  com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior getBehavior();
    descriptor: ()Lcom/sun/javafx/scene/control/behavior/ComboBoxBaseBehavior;

[nix-shell:~]$ javap -cp $CP -s com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior | grep behavior\.ComboBoxBaseBehavior
public class com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior<T> extends com.sun.javafx.scene.control.behavior.BehaviorBase<javafx.scene.control.ComboBoxBase<T>> {
  public com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior(javafx.scene.control.ComboBoxBase<T>);
```

**Comment by hrhino** [comment]
I'm tentatively assigning this to 2.13.1 simply because I also cannot think of a workaround, and while javafx is pretty horrid code, this seems like the sort of thing someone else would do, too.

**Comment by hrhino** [comment]
A minimization:
```[nix-shell:/code/scala]$ tail -n+1 test/files/pos/t11584/*
==> test/files/pos/t11584/Fiddle_1.java <==
package t11584;

public class Fiddle_1 {
    public Misbehavior_1 misbehave() { throw new Error(); }
}
==> test/files/pos/t11584/Misbehavior_1.java <==
package t11584;

public interface Misbehavior_1<T> {}
==> test/files/pos/t11584/Riddle_1.java <==
package t11584;

public class Riddle_1 extends Fiddle_1 {
    @Override public Misbehavior_1 misbehave() { throw new Error(); }
}
==> test/files/pos/t11584/Why_2.scala <==
import t11584._

class Why extends Riddle_1
```

**Comment by OlegYch** [comment]
fwiw getting same error with CUP generated parsers

**Comment by hrhino** [comment]
fwiw this looks like a decent weekend project; I'll have a look.

**Comment by hrhino** [comment]
@olegych if you attach a small example of whatever a "CUP generated parser" looks like I'll use it as a test case as well, if it doesn't rely on some other library.

**Comment by OlegYch** [comment]
it looks just like your minimization, except it uses `java.lang.Class` instead of Misbehavior_1

**Comment by hrhino** [comment]
NTS: culprit is apparently scala/scala@fde215f606dc63813bea3b6bc64176aa551b40ce.

**Comment by NthPortal** [comment]
cc @adriaanm

**Comment by SethTisue** [comment]
#11588 has another example

**Comment by szeiger** [comment]
As discussed in yesterday's team meeting, this is a hard problem that may not have a quick solution and we shouldn't hold up 2.13.1 for it.
