### ISSUE TITLE
Regression trouble inferring type of java wildcard in 2.12.10

### ISSUE THREAD

**Issue by frosforever** [scala/bug#11905]
## reproduction steps

Using the dependency: `"io.grpc" % "grpc-core" % "1.18.0"`, the following code fails to compile in `2.12.10` and `2.13.1` but compiles just fine in `2.11.12`

```scala
import io.grpc.ManagedChannelBuilder

trait Test {
  val grpcChannel = ManagedChannelBuilder
    .forAddress(
      "host",
      1234
    )
    .maxInboundMessageSize(20)
    .usePlaintext()
    .build()
}
```

## problem
Fails with:
```scala
 value usePlaintext is not a member of ?0
[error] possible cause: maybe a semicolon is missing before `value usePlaintext'?
[error]     .usePlaintext()
[error]      ^
[error] one error found
```

## expectation
This compiles fine in `2.11.12`. It also compiles if `Test` is an `object` instead of a `trait`. From what I can tell, this was also an issue in `2.10` that got fixed in `2.11` but has now come back in `2.12` and `2.13`. 

See also https://github.com/grpc/grpc-java/issues/2813#issuecomment-346506933 and https://stackoverflow.com/questions/44899041/unable-to-build-grpc-managedchannel-with-scala for historical context.

**Comment by nogurenn** [comment]
I don't know what `?0`, but when I tried separating the last two method calls, the compiler complained:
```scala
val grpcChannel = ManagedChannelBuilder.forAddress("host",1234).maxInboundMessageSize(20) 
val x = grpcChannel.usePlaintext().build()

cmd2.sc:3: value usePlaintext is not a member of Object
val x = grpcChannel.usePlaintext().build()
                    ^
Compilation Failed

// Another thing I found is that the returned value of `.forAddress()`
// is properly seen(?) by the compiler
val grpcChannel = ManagedChannelBuilder.forAddress("host",1234)
// ...
res: () => ManagedChannelBuilder[?0] forSome { type ?0 <: ManagedChannelBuilder[?0] }

// but scala only sees the returned value
// of `.maxInboundMessageSize()` as `[java.lang.]Object` / ?0
```

So, in summary,
```scala
// given this call chain
ManagedChannelBuilder.forAddress("host",1234).maxInboundMessageSize(20).usePlaintext().build()

// scala can see this returned value
.forAddress() -> static ManagedChannelBuilder<?>

// but it cannot see the next returned value in the chain
.maxInboundMessageSize() -> T

// so for some reason, scala complains with seeing
.maxInboundMessageSize() -> Object (but not writing it as java.lang.Object)
```

**Comment by SethTisue** [comment]
`?0` is a sure sign an existential type is involved

with `-Xlint`, `.maxInboundMessageSize(20)` produces the warning `warning: inferred existential type ?0 forSome { type ?0 <: io.grpc.ManagedChannelBuilder[?0] }, which cannot be expressed by wildcards, should be enabled by making the implicit value scala.language.existentials visible`, so that confirms that an existential type is involved

and `?0 forSome { type ?0 <: io.grpc.ManagedChannelBuilder[?0] }` shows that F-bounded polymorphism is in play here

it's odd (and probably significant) that in the REPL, it compiles without the trait wrapper

it also compiles if you use `def` instead of `val`

**Comment by SethTisue** [comment]
I've added the f-bounds label, which is then helpful for finding related tickets. Perhaps this is a duplicate of #4745?

**Comment by SethTisue** [comment]
(and btw thx @nogurenn for the triage help!)

**Comment by frosforever** [comment]
@SethTisue that sounds right. Not sure what version #4745 was against but it's interesting this _did_ work for scala `2.11.12` and has now regressed.

**Comment by SethTisue** [comment]
fixed in Dotty. tested via `cs launch io.grpc:grpc-core:1.18.0 dotty-repl`

**Comment by SethTisue** [comment]
> Not sure what version #4745 was against but it's interesting this did work for scala 2.11.12 and has now regressed.

#4745 was likely reported against 2.10.x. The example here in this ticket fails on 2.10.7, so it could still be a duplicate.
