### ISSUE TITLE
Protected object (sometimes) visibile when it shouldn't

### ISSUE THREAD

**Issue by dragos** [scala/bug#11554]
When the access and the definition are compiled separately, Scala lets this one pass. When compiled together, it issues an error:

```scala
// file a.scala
package core.test

protected object Exec {
  def isBool: Boolean = false
}
```

```scala
// file b.scala
package bar

import core.test._

class Test {
  Exec.isBool // Exec should not be visible herea
}
```

Compiling these two together gives the expected error:

```
visibility2.scala:6: error: not found: value Exec
  Exec.isBool // Exec should not be visible here
  ^
one error found
```

Compiling one and then the other succeeds, though:

```
$ scalac -d /tmp/classes/ a.scala 
$ scalac -d /tmp/classes/ -cp /tmp/classes/ b.scala 
$
```

Scala version: 2.12.8

**Comment by hrhino** [comment]
That's unfortunate. The problem is that this `protected` is less restrictive than the JVM's, so it's `ACC_PUBLIC` in bytecode, so the fact that it's protected isn't known until it's unpickled, and it's not unpickled until the `Ident("Exec")` tree is already typechecked (access-checked).
