### ISSUE TITLE
Implicit conversion not triggering for pairs 

### ISSUE THREAD

**Issue by txsmith** [scala/bug#12411]
## reproduction steps

using Scala 2.12.13 / 2.13.6,

```scala
import scala.language.implicitConversions

implicit def pairConv[A](x: (String, A)): (String, String) = (x._1, "String")

def m(pair: (String, String)*): Unit = {}

m(("x", 123)) // fails with a type mismatch

// Uncommenting the def below 'fixes' the compiler error, but only on 2.12
// def m(a: Int, pairs: (String, String)*): Unit = ???
```

## problem
I would expect that calling `m(("x", 123))` would result in `pairConv` being applied implicitly, but instead I get a type mismatch:
```
[error]  found   : Int(123)
[error]  required: String
[error]   m(("x", 123))
```

It might be good to note that the behavior changes slightly between 2.12 and 2.13.
On 2.12, adding that overload to `m` "fixes" the issue. On 2.13, that does not hold though.
Furthermore the snippet above works on 2.13 but only when applying one argument, the same error appears with multiple.
Lastly, for both versions, defining `m` to take a single pair instead of var-args also causes the issue.

**Comment by joroKr21** [comment]
It might help if you show the compiler output with `-Xlog-implicits` enabled

**Comment by txsmith** [comment]
There do not appear any logs with that flag. This is the full output of a clean compile:
```
sbt:implicit> reload;clean;compile
[info] welcome to sbt 1.5.2 (AdoptOpenJDK Java 11.0.8)
[info] loading global plugins from /Users/thomas/.sbt/1.0/plugins
[info] loading settings for project implicit-build from plugins.sbt ...
[info] loading project definition from /Users/thomas/dev/implicit/project
[info] loading settings for project implicit from build.sbt ...
[info] set current project to implicit (in build file:/Users/thomas/dev/implicit/)
[success] Total time: 0 s, completed 9 Jun 2021, 12:40:21
[info] compiling 1 Scala source to /Users/thomas/dev/implicit/target/scala-2.13/classes ...
[error] /Users/thomas/dev/implicit/src/main/scala/main.scala:12:11: type mismatch;
[error]  found   : Int(123)
[error]  required: String
[error]   m(("x", 123))
[error]           ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 9 Jun 2021, 12:40:21
sbt:implicit>
```

You can play with a sample here: https://scastie.scala-lang.org/l1Dni6FWQTWlaH9x7NfyiQ

**Comment by joroKr21** [comment]
This works:
```scala
val pair = ("x", 123)
m(pair)
```

**Comment by som-snytt** [comment]
Yes, it doesn't get out of picking type args for the tuple, so `m(("ok", 42): (String, Int))`.

It will use an `Int => String` implicit. And from `Vtyper` it also looks for a conversion of the receiver, for a better `m`.

**Comment by txsmith** [comment]
That sounds to me like a bug. As an end-user is see no reason why 
```
val pair = ("x", 123)
m(pair)
```
would compile but
```
m(("x", 123))
```
would not. Semantically they're the same thing after all.

**Comment by joroKr21** [comment]
Not quite because expected types propagate from the outer expression to the inner one. So it infers that it needs a tuple `(String, String)` as the type parameters of the `Tuple2` constructor. Once it sees the `Int <-> String` mismatch it looks for an implicit conversion but it doesn't backtrack to look for an implicit conversion of the outer expression. Backtracking with implicit search would be very expensive in general.

**Comment by txsmith** [comment]
I see, so the way to avoid this would be to have the compiler not go down into the tuple when inferring the type. I think this is a workable solution for us:

```scala
import scala.language.implicitConversions

case class StringPair(key: String, value: String)

implicit def pairConv[A](x: (String, A)): StringPair = StringPair(x._1, x._2.toString)
def m(pair: StringPair*): Unit = println(pair)

m("x" -> 1, "y" -> 2)
```

**Comment by martijnhoekstra** [comment]
Should this be closed? That the presence of an unselected overload makes it compile is pretty difficult to swallow as not-a-bug.

**Comment by joroKr21** [comment]
The overload prevents the expected type from propagating to the argument. Scala 3 has the same problem.
