### ISSUE TITLE
parser error: multiple if-guards on the same line in for-comprehensions

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#12323]
using Scala 2.13.4

According to scala syntax (https://www.scala-lang.org/files/archive/spec/2.13/13-syntax-summary.html)
```
Generator ::=  Pattern1 ‘<-’ Expr {[semi] Guard | semi Pattern1 ‘=’ Expr}
```
several guards on the same line is a valid code.
But unfortunately, if you place several guards on the same line, starting from a new line, a compilation error occurs.

```scala
for {
  x <- 1 to 5 if true if true
} yield x

for {
  x <- 1 to 5 if true
  if true
} yield x

for {
  x <- 1 to 5
  if true if true
} yield x

for {
  x <- 1 to 5
  if true
  if true
} yield x
```

![image](https://user-images.githubusercontent.com/3989292/105838504-36680880-5fe1-11eb-9a1a-02907165e0fe.png)

related issue: https://youtrack.jetbrains.com/issue/SCL-13220

**Comment by unkarjedy** [comment]
Note that it works fine in Scala 3.0.0-M3.
(Though looks like Scala 3 syntax reference says that semicolon is obligatory everywhere:
`Enumerators       ::=  Generator {semi Enumerator | Guard}`)

![image](https://user-images.githubusercontent.com/3989292/105839022-f5242880-5fe1-11eb-969e-1ca464ae498d.png)

**Comment by dwijnand** [comment]
My assumption is we need to fix the spec, not the other way round.  But let's see what other say (including in the Dotty PR).

**Comment by som-snytt** [comment]
Quick PR.

Full disclosure, I once advocated https://github.com/scala/scala/pull/3463/files

**Comment by SethTisue** [comment]
I think I lean towards changing the Scala 2 implementation to match Scala 3's, and changing the Scala 3 spec to match Scala 2's.

It is well established that a guard doesn't need a semicolon before it; and it's well established that you can have multiple guards. So I don't see a good grounds for forbidding any of the four examples above. `if a if b` on the same line is a bit silly since it could be `if a and b`, but it's not really the spec's job to forbid things that are a bit silly.

Regardless, I'd like to see what other people think, and in particular, how the Dotty team reacts to https://github.com/lampepfl/dotty/pull/11215 .

There is one piece of information I feel I'm missing here in order to really feel confident in any decision, namely: how is it that the Scala 3 spec ended up being different than the Scala 2 one on this point? Who did that when and why? I'll ask on the Dotty PR.

**Comment by SethTisue** [comment]
> I think I lean towards changing the Scala 2 implementation to match Scala 3's, and changing the Scala 3 spec to match Scala 2's.

confirmed by Martin on the Dotty PR
