### ISSUE TITLE
Inscrutible type mismatch after not auto-applying under -Xsource:3

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12006]
## reproduction steps

```scala
$ scala -nobootcp -Xsource:3
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.

scala> class C(s: => java.io.InputStream)
class C

scala> class D(u: java.net.URL) extends C(u.openStream)
                                            ^
       error: type mismatch;
        found   : java.io.InputStream
        required: Int

scala> class D(u: java.net.URL) extends C(u.openStream())
class D
```

## problem

`sys.process` doesn't compile under `-Xsource:3`. The error message is not illuminating. I hope it has nothing to do with `read`.

**Comment by dwijnand** [comment]
Regressed since 2.13.0:

```
$ scala -nc -2.13.0 -Xsource:3 -e 'class C(s: => java.io.InputStream); class D(u: java.net.URL) extends C(u.openStream)'
/var/folders/yh/qsn4cxqj47gbhh9_prlxqy3r0000gn/T/scalacmd15663462180116821089.scala:1: error: type mismatch;
 found   : java.io.InputStream
 required: Int
class C(s: => java.io.InputStream); class D(u: java.net.URL) extends C(u.openStream)
                                                                         ^
$ scala -nc -2.12.11 -Xsource:3 -e 'class C(s: => java.io.InputStream); class D(u: java.net.URL) extends C(u.openStream)'
$
```

**Comment by dwijnand** [comment]
Either it should compile while emitting a warning, or without `-Xsource:3` it should emit a warning.  Either way, it would be great to make the message clearer.

**Comment by dwijnand** [comment]
Added to 2.13.3, for consideration.

**Comment by SethTisue** [comment]
anyone have a guess what PR might be responsible? (someone want to try bisecting it?)

**Comment by SethTisue** [comment]
since it's under `-Xsource:3`, not a 2.13.3-blocker

**Comment by som-snytt** [comment]
This must have been when I tested the codebase's future-friendliness. The goal was to be able to say that `-Xsource:3` is sharp like a good chef's knife not like a broken beer bottle.

**Comment by eed3si9n** [comment]
According to git bisect, https://github.com/scala/scala/pull/7660/commits/45201171aef3b33fb49955ef94ee085a275ecdbb is the first bad commit.

**Comment by eed3si9n** [comment]
Here's my PR for this to make the snippet compile - https://github.com/scala/scala/pull/9027

**Comment by eed3si9n** [comment]
So it looks like the snippet in question can be interpreted in two different ways:

1. `InputStream` is a SAM of `def read(): Int`, and `C(u.openStream)` requires an eta-expansion from openStream method to `() => Int`.
2. `u.openStream` needs auto application `()`.

Under -Xsource:3 Scala 2.13.2 takes the first interpretation since https://github.com/scala/scala/pull/7660. In https://github.com/scala/scala/pull/9027 I added more checks to see if the result type matches up not just checking for arity.
