### ISSUE TITLE
TastyReader bug on cats-core

### ISSUE THREAD

**Issue by adpi2** [scala/bug#12241]
## reproduction steps

Using Scala 2.13.4 and `-Ytasty-reader` in an sbt project that depends on `cats-core_3.0.0-M1`
```scala
val foo = project
  .in(file("foo"))
  .settings(
    scalaVersion := "2.13.4",
    libraryDependencies ++= Seq(
      "org.typelevel" % "cats-core_3.0.0-M1" % "2.3.0-M2",
    ),
    scalacOptions += "-Ytasty-reader"
  )
```

and contains a single Scala source file:
```scala
package foo

import cats.syntax.all._

object Main extends App
```

## problem

Compilation fails with the following error:

```shell
[error] /foo/src/main/scala/foo/Example.scala:5:21: can't find type in parents of trait cats.Show: cats.Show.ContravariantShow; perhaps it is missing from the classpath.
[error] object Main extends App
[error]                     ^
[error] one error found
[error] (foo / Compile / compileIncremental) Compilation failed
```

**Comment by adpi2** [comment]
Also this piece of code gives the same error but it is more rational in this context:

```scala
package foo

import cats.syntax.AllSyntaxBinCompat

object all extends AllSyntaxBinCompat
```

```shell
[error] /foo/src/main/scala/foo/Example.scala:5:8: can't find type in parents of trait cats.Show: cats.Show.ContravariantShow; perhaps it is missing from the classpath.
[error] object All extends AllSyntaxBinCompat
[error]        ^
```

**Comment by adpi2** [comment]
Also, this does not compile
```scala
package foo

import cats.syntax.ShowSyntax
```
whereas this compiles:
```scala
package foo

import cats.Show.ContravariantShow
import cats.syntax.ShowSyntax
```

**Comment by adpi2** [comment]
And this one does compile and run:

```
package foo

import cats.Show

object Foo extends Show[Int] {
  override def show(t: Int): String = t.toString()
}

object Main extends App {
  println(Foo.show(2))
}
```

**Comment by SethTisue** [comment]
fyi @bishabosha

**Comment by bishabosha** [comment]
Thank you for all the info

**Comment by bishabosha** [comment]
The following minimised snippets reproduce the same error:

```scala
// compile with scala 3.0.0-M1
package cats

object syntax extends Show.ToShowOps

trait Show extends Show.ContravariantShow

object Show {

  trait ContravariantShow

  trait ToShowOps

}
```

```scala
// compile with Scala 2.13.4
package foo

import cats.syntax._

object Main extends App

```
