### ISSUE TITLE
Scaladoc method filtering stopped working in 2.12.9

### ISSUE THREAD

**Issue by smarter** [scala/bug#11672]
1. Go to https://www.scala-lang.org/api/2.12.8/scala/collection/immutable/List.html
2. Type stuff in the input field below the class documentation, observe the method list being filtered accordingly
3. Now go to https://www.scala-lang.org/api/2.12.9/scala/collection/immutable/List.html and do the same, observe that nothing gets filtered.

Additionally, note that filtering https://www.scala-lang.org/api/2.13.0/scala/collection/immutable/List.html does work.

**Comment by martijnhoekstra** [comment]
Possibly related, console tells me

```
Uncaught TypeError: Cannot set property 'pointerover' of undefined
    at String.<anonymous> (jquery.panzoom.min.js:9)
    at Function.each (jquery.min.js:2)
    at jquery.panzoom.min.js:9
    at jquery.panzoom.min.js:9
    at jquery.panzoom.min.js:9
```
```
jquery.min.js:2 jQuery.Deferred exception: $(...).panzoom is not a function TypeError: $(...).panzoom is not a function
    at HTMLDocument.<anonymous> (https://www.scala-lang.org/files/archive/api/2.12.9/lib/template.js:7:51)
    at e (https://www.scala-lang.org/files/archive/api/2.12.9/lib/jquery.min.js:2:29453)
    at t (https://www.scala-lang.org/files/archive/api/2.12.9/lib/jquery.min.js:2:29755) undefined
k.Deferred.exceptionHook @ jquery.min.js:2
```
```
jquery.min.js:2 Uncaught TypeError: $(...).panzoom is not a function
    at HTMLDocument.<anonymous> (template.js:7)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)
```

**Comment by martijnhoekstra** [comment]
@exoego maybe related to https://github.com/scala/scala/pull/8179 ?

**Comment by SethTisue** [comment]
volunteer to attempt a fix for 2.12.10? (which we'd like to build within the next week or so)

**Comment by exoego** [comment]
I will open a PR

**Comment by exoego** [comment]
Opened a PR https://github.com/scala/scala/pull/8395
