### ISSUE TITLE
Implicit override within macros fails to detect usage in 2.12.4

### ISSUE THREAD

**Issue by devshorts** [scala/bug#10614]
I'll be honest, I am not 100% sure what _exactly_ the issue is but I have narrowed down the problem in this repo: https://github.com/devshorts/scala-implicits-error

The gist is I have a macro that is [creating a reified class](https://github.com/devshorts/scala-implicits-error/blob/master/src/main/scala/io.paradoxical/App.scala#L40) that will look like the following when expanded:

```
import DefaultConversions._
import AsWrapper._

new Conversion[A] {
  override def from(m: A): String = {
     m.as
  }
}
```

Where `.as` is an extension method that summons an implicit to convert `m` to a string. 
```
object AsWrapper {
  implicit def wrapped[A](a: A) = As(a)
}

case class As[A](a: A) {
  implicit def as(implicit c: Conversion[A]): String = c.from(a)
}

trait Conversion[A] {
  def from(a: A): String
}
```

In the macro I include some default imports that provide well known conversions (long -> string):

```
trait LowPri {
  implicit val longConvert: Conversion[Long] = new Conversion[Long] {
    override def from(a: Long) = a.toString
  }
}

object DefaultConversions extends LowPri
```

In the following test I provide an implicit that overrides the implicit that was pulled in in the macro:

```
class Tests extends FlatSpec with Matchers {
  "A test" should "run" in {
    implicit object priorityConverter extends Conversion[Long] {
      override def from(a: Long) = "abc"
    }

    MacroImplicit.convert[Long].from(1) shouldEqual "abc"
  }
}
```

In 2.12.3 this test passes fine. In 2.12.4 I get an error saying that the `priorityConverter` is not used.

```
[info] Compiling 1 Scala source to /Users/antonkropp/src/paradox/macro-test/target/scala-2.12/test-classes ...
[error] /Users/antonkropp/src/paradox/macro-test/src/test/scala/io.paradoxical/AppSpec.scala:7:21: local object priorityConverter in value <local Tests> is never used
[error]     implicit object priorityConverter extends Conversion[Long] {
[error]                     ^
[error] one error found
[error] (test:compileIncremental) Compilation failed
```

If I move the scope of the implicit object:

```
class Tests extends FlatSpec with Matchers {
  implicit object priorityConverter extends Conversion[Long] {
    override def from(a: Long) = "abc"
  }
  
  "A test" should "run" in {

    MacroImplicit.convert[Long].from(1) shouldEqual "abc"
  }
}
```

It works fine in 2.12.4

Hopefully this repo makes sense, I'm not sure whats going on other than it seems inconsistent across versions and I have tests that break :p

**Comment by SethTisue** [comment]
dupe of #10579 and multiple other tickets
