### ISSUE TITLE
case class companion object generates two apply methods

### ISSUE THREAD

**Issue by DieBauer** [scala/bug#11207]
I've encountered an issue when upgrading the compiler to 2.12.7. 

I have a piece of java code that uses the apply method of a scala case class. 

```java
final MyClass myClass = MyClass.apply(1, 2, 3L, 4)
```

When using `MyClass` compiled with Scala 2.12.7, I get: `incompatible types: java.lang.Object cannot be converted to MyClass. `

Where, before it compiled fine.  

I'm now looking into the generated bytecode and can see this. 

Test.scala:
```scala
case class MyClass(a: Int, b: Int, c: Long, d: Int)
```

```sh
$ scalac Test.scala
$ scala -classpath .
Welcome to Scala 2.12.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> :javap -p MyClass
Compiled from "Test.scala"
public class MyClass implements scala.Product,scala.Serializable {
  private final int a;
  private final int b;
  private final long c;
  private final int d;
  public static java.lang.Object apply(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object);
  public static scala.Option<scala.Tuple4<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object>> unapply(MyClass);
  public static MyClass apply(int, int, long, int);
  public static scala.Function1<scala.Tuple4<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object>, MyClass> tupled();
  public static scala.Function1<java.lang.Object, scala.Function1<java.lang.Object, scala.Function1<java.lang.Object, scala.Function1<java.lang.Object, MyClass>>>> curried();
  public int a();
  public int b();
  public long c();
  public int d();
  public MyClass copy(int, int, long, int);
  public int copy$default$1();
  public int copy$default$2();
  public long copy$default$3();
  public int copy$default$4();
  public java.lang.String productPrefix();
  public int productArity();
  public java.lang.Object productElement(int);
  public scala.collection.Iterator<java.lang.Object> productIterator();
  public boolean canEqual(java.lang.Object);
  public int hashCode();
  public java.lang.String toString();
  public boolean equals(java.lang.Object);
  public MyClass(int, int, long, int);
}
```

When doing the same exercise on scala 2.12.6 I get:

```sh
$ scalac Test.scala
$ scala -classpath .
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> :javap -p MyClass
Compiled from "Test.scala"
public class MyClass implements scala.Product,scala.Serializable {
  private final int a;
  private final int b;
  private final long c;
  private final int d;
  public static scala.Option<scala.Tuple4<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object>> unapply(MyClass);
  public static MyClass apply(int, int, long, int);
  public static scala.Function1<scala.Tuple4<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object>, MyClass> tupled();
  public static scala.Function1<java.lang.Object, scala.Function1<java.lang.Object, scala.Function1<java.lang.Object, scala.Function1<java.lang.Object, MyClass>>>> curried();
  public int a();
  public int b();
  public long c();
  public int d();
  public MyClass copy(int, int, long, int);
  public int copy$default$1();
  public int copy$default$2();
  public long copy$default$3();
  public int copy$default$4();
  public java.lang.String productPrefix();
  public int productArity();
  public java.lang.Object productElement(int);
  public scala.collection.Iterator<java.lang.Object> productIterator();
  public boolean canEqual(java.lang.Object);
  public int hashCode();
  public java.lang.String toString();
  public boolean equals(java.lang.Object);
  public MyClass(int, int, long, int);
}
```

A duplicate `apply` method is generated in scala 2.12.7 with the following signature:  
`public static java.lang.Object apply(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object);`
and it seems this one is being picked in my Java project, causing the exception. 
It seems that this is an unintended breaking change between these two versions.  

Of course a workaround is using the new keyword: 
```
final MyClass myClass = new MyClass(1, 2, 3L, 4)
```

**Comment by martin-g** [comment]
I've faced the same problem while upgrading to 2.12.7

**Comment by lrytz** [comment]
Commented here for the reason we get more forwarders: https://github.com/scala/scala/pull/7035/files#r226274350

**Comment by lrytz** [comment]
However, @DieBauer and @martin-g, I cannot reproduce the problem that you are having with javac. For me, javac compiles the `apply` call successfully:

```
$> cat Test.scala
case class MyClass(a: Int, b: Int, c: Long, d: Int)
$> scalac -version
Scala compiler version 2.12.7 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
$> scalac Test.scala
$> cat Test.java
public class Test {
  final MyClass myClass = MyClass.apply(1, 2, 3L, 4);
}
$> javac -version
javac 1.8.0_181
$> javac Test.java -cp ../build/quick/classes/library:.
$> scala -e "println((new Test).myClass)"
MyClass(1,2,3,4)
$>
```

Which version of Java are you using? Where do you get the error: command line / build tool / IDE?

**Comment by martin-g** [comment]
I had the problem both in Sbt and IDEA. 
In my case the Scala case class is in module1. The Java class is in module2 that depends on module1.

Let me try to reproduce it!

**Comment by martin-g** [comment]
I also was not able to reproduce it in a mini app. 
`javap` shows the extra `apply()` method with all parameters being `java.lang.Object` but it doesn't break neither Sbt nor IDEA.

**Comment by hrhino** [comment]
Another workaround is to explicitly add a companion object (this prevents it from tacitly extending a `FunctionN` class, which is where the bridge is coming from).

**Comment by DieBauer** [comment]
Alright, it was a bit more complex than I initial thought. I think the gist is that the java types are not primitives, but boxed. 

I've created a reproducer: https://github.com/DieBauer/reproducer-scala on 2.12.6 in build sbt it compiles, setting it to 2.12.7 it doesn't.

```
reproducer/java/a/Test.java:7:1: incompatible types: java.lang.Object cannot be converted to com.reproducer.module.util.MyClass
```

**Comment by lrytz** [comment]
@DieBauer thanks! To summarize it here:

Scala:
```scala
case class MyClass(a: Int)
```

Java:
```java
MyClass.apply(Integer.valueOf(1));
```

```
Test.java:5: error: incompatible types: Object cannot be converted to MyClass
  final MyClass myClass = MyClass.apply(Integer.valueOf(1));
                                       ^
```

So javac picks the `(Object)Object` overload, even though it's marked `bridge` in bytecode. It's a bit unfortunate because it kind of introduces a new version of https://github.com/scala/bug/issues/11061, the bug that was actually fixed in https://github.com/scala/scala/pull/7035.

I think it's limited to the case of auto-unboxing. For non-primitives, the bridge method is less specific than the non-bridge, so javac should pick the non-bridge.

Also it looks like there's no issue with return types, the following compiles fine:

Scala:
```scala
abstract class A[T] { def f: T }
object B extends A[Int] { def f = 1 }
```

Java:
```java
final int a = B.f();
final Integer b = B.f();
final Object c = B.f();
```

So it looks like the scope of the bug is quite limited. I'm a bit worried to fix it for 2.12.8, because it would remove methods that exist in 2.12.7, which is binary incompatible. Since it's already fixed in 2.13, I think we should just do nothing. Unfortunately...

**Comment by gehnaphore** [comment]
Our project uses a big hierarchy of case classes including which is processed and transformed across many stages by both Scala and Java code, and this breaks a *lot* of our code.

**Comment by SethTisue** [comment]
hmm, maybe a 2.12-only flag that would let people opt in to the fix, if they are confident doing so won't cause headaches?

**Comment by lrytz** [comment]
That's an idea, we could backport the 2.13 fix under a flag. But it wouldn't help for libraries fetched from maven (that are compiled without that flag).

**Comment by DieBauer** [comment]
By the way, if you have a case class that has a mix of `AnyRef` and primitive fields, and you call it from Java (boxed primitive) with the generated `apply` method a second compiler errors gets emitted: 

```scala
class X
case class MyClass(a: Int, aa: Int, b: String, c: X)
```

```java
final MyClass myClass = MyClass.apply(1, Integer.valueOf(1), "bla", new X());
```

```
Test.java:3:1: reference to apply is ambiguous
[error]   both method apply(java.lang.Object,java.lang.Object,java.lang.Object,java.lang.Object) in MyClass and method apply(int,int,java.lang.String,X) in MyClass match
[error]             MyClass.apply(1, Integer.valueOf(1), "bla", new X());
[error] Test.java:3:1: incompatible types: java.lang.Object cannot be converted to MyClass
[error]             MyClass.apply(1, Integer.valueOf(1), "bla", new X());
```

So I think the potential impact is that any library that gets compiled with 2.12.7 (and if this is not rolled back, further future 2.12.x releases) which is used from a Java project and passes boxed primitives to the apply method is broken.

**Comment by SethTisue** [comment]
once we have a plan, we should probably publicize it on https://contributors.scala-lang.org/t/library-authors-rebuild-on-2-12-7-to-improve-callability-from-java-on-jdk-11/2465/7

**Comment by shawjef3** [comment]
This also causes serialization surprises. https://users.scala-lang.org/t/serialversionuid-change-between-scala-2-12-6-and-2-12-7/3478

**Comment by dwijnand** [comment]
Fixed in https://github.com/scala/scala/pull/7383.
