### ISSUE TITLE
(2.12.6) error during expansion of this match (this is a scalac bug)

### ISSUE THREAD

**Issue by gzoller** [scala/bug#11162]
I receive this error message in multiple places in my code.  I've included a snip here, compiled against 2.12.6.  Also tried 2.12.4 and saw the same problem.  

For full effect clone and build https://github.com/gzoller/ScalaJack on branch feature/v7_staging

```
      json match {
        case JsonArray(x) =>
          builder.append('[')
          ops.foreachArrayElement(x.asInstanceOf[ops.ArrayElements], { (index, element) =>
            if (index > 0) {
              builder.append(",")
            }
            helper(element)
          })
          builder.append(']')
```

**Comment by gzoller** [comment]
Narrowed the problem.  If I compile against 2.12.3 my code compiles with no problems.  Building the same code against 2.12.4+ produces these match errors.  Did something change?

**Comment by SethTisue** [comment]
can the bug be demonstrated with a minimized piece of standalone (no dependencies) code?

**Comment by gzoller** [comment]
Surely.  Check this out:  https://github.com/gzoller/scalabug

It's a minimal project with no external dependencies and complexity reduced to a minimal level.

It compiles and runs fine under Scala 2.12.3, but not 2.12.4+.

**Comment by hrhino** [comment]
`git bisect` blames scala/scala@5197256b44f34fa50ed468954d0bfb3bc469477d.

**Comment by hrhino** [comment]
Minimized even more:
```scala
// Start writing your ScalaFiddle code here
class Ops[X] { type T }

object Meh {
  def unapply[X](i: Int)(implicit ops: Ops[X]): Option[ops.T] = None
}

def foo[X](implicit ops: Ops[X]): Unit = {
  def bar() = 1 match { case Meh(z) => z }
  bar()
}

// t11162.scala:9: error: error during expansion of this match (this is a scalac bug).
// The underlying error was: type mismatch;
// found   : ops.T
// required: ops.T
//    def bar() = 1 match { case Meh(z) => z }
//                  ^
```

**Comment by adriaanm** [comment]
looks like this is the culprit (please read modulo `s/craz/fanc/`):
```
    // bug#6130 can't really say what the result type is without referring to the binder we're extracting,
    // as an unapply's result type could depend on its argument, e.g. crazy stuff like `def unapply(x: T): Option[(x.T, x.U)]`
    // NOTE: we skip a potential implicit method type here -- could this be another avenue of craziness where the result type depends on the input?
    private def unapplyResultType(extractedBinder: Symbol = unapplySelector): Type =
```
