### ISSUE TITLE
Unsupported generic tuple error when using Scala 3 code in Scala 2

### ISSUE THREAD

**Issue by jadenPete** [scala/bug#13124]
## Reproduction steps

Scala 2 version: 2.13.16
Scala 3 version: 3.6.3

1. Clone this minimum reproducability case:
https://github.com/jadenPete/scala-unsupported-generic-tuple-bug-reproduction

2. Run `sbt compile`
3. Observe the following compilation error:
```
[error] Unsupported Scala 3 generic tuple type scala.Tuple in bounds of type MirroredElemLabels; found in trait scala.deriving.Mirror.
```

## Problem

I'd expect this to compile. I acknowledge that this is an unusual use case (`Foo` should be an `object`, not a `case object`), but we stumbled upon it during our Scala 2 -> Scala 3 migration and I thought it'd be valuable to report. If this is expected behavior and not a bug, feel free to close this issue.

**Comment by roman0x58** [comment]
I’m getting the same error when using the 2.13.18 module after upgrading to Scala 3.8.1 from 3.7.4,
`createCodecProviderIgnoreNone` the scala 2 macro from mongo-java-driver
```
Unsupported Scala 3 generic tuple type scala.*: in result; found in constructor <init> in class scala.Tuple2.
[error]     createCodecProviderIgnoreNone[IdGen]()
```
