### ISSUE TITLE
`error during expansion of this match (this is a scalac bug)` after upgrade from 2.13.10 to 2.13.11

### ISSUE THREAD

**Issue by danielleontiev** [scala/bug#12814]
The following code causes compilation error under 2.13.11

File `bug.sc`

```scala
//> using scala "2.13.11"

sealed trait Common
sealed trait One extends Common
sealed trait Two extends Common


trait Module[C <: Common] {
  val name: String
  type Narrow = C
  def narrow: PartialFunction[Common, C]
}

object ModuleA extends Module[One] {
  val name = "A"
  val narrow: PartialFunction[Common, Narrow] = {
    case cc: Narrow => cc
  }
}

object ModuleB extends Module[ModuleA.Narrow] {
  val name = "B"
  val narrow: PartialFunction[Common, Narrow] = {
    case cc: Narrow => cc
  }
}

object ModuleC extends Module[Two] {
  val name = "C"
  val narrow: PartialFunction[Common, Narrow] = {
    case cc: Narrow => cc
  }
}

object ModuleD extends Module[One with Two] {
  val name = "D"
  val narrow: PartialFunction[Common, Narrow] = {
    case cc: Narrow => cc
  }
}

val one    = new One {}
val two    = new Two {}
val oneTwo = new One with Two {}

Seq(ModuleA, ModuleB, ModuleC, ModuleD).foreach { module =>
  println(s"${module.name} at One    = ${module.narrow.isDefinedAt(one)}")
  println(s"${module.name} at Two    = ${module.narrow.isDefinedAt(two)}")
  println(s"${module.name} at OneTwo = ${module.narrow.isDefinedAt(oneTwo)}")
  println("-" * 10)
}

```

Run with:

```bash
scala-cli bug.sc
```

Compiler error:

```
Compiling project (Scala 2.13.11, JVM)
[error] ./bug.sc:23:49
[error] error during expansion of this match (this is a scalac bug).
[error] The underlying error was: cyclic aliasing or subtyping involving type Narrow
[error]   val narrow: PartialFunction[Common, Narrow] = {
[error]                                                 ^
Error compiling project (Scala 2.13.11, JVM)
Compilation failed
```

It was not the case under 2.13.10, where code compiles successfully.

Run under 2.13.10, change the first line to

```scala
//> using scala "2.13.10"
```

and run as before

```bash
scala-cli bug.sc
```

**Comment by lrytz** [comment]
Caused by https://github.com/scala/scala/pull/10247 (tested by reverting it on top of current 2.13.x)

**Comment by lrytz** [comment]
Workaround: use the `-Yrecursion 1` compiler flag. Default is 0.

**Comment by lrytz** [comment]
Canonical example:

```scala
trait A[X] { type T = X }
object B extends A[String]
object C extends A[B.T] {
  def f: C.T = "hai"
}
```

The problem is in `checkNonCyclic(C.T)`, which locks on the symbol for the `T` twice. The alias `T` is expanded twice (`C.T` => `B.T` => `String`) but in the second iteration it's already locked.

**Comment by abebeos** [comment]
Related/possible duplicate https://github.com/scala/bug/issues/12622



> Workaround: use the `-Yrecursion 1` compiler flag. Default is 0.

@lrytz , is this a workaround, or must(!) this flag be used for code like this?

- #12911

Sidenote: Shouldn.t the https://github.com/scala/bug/labels/regression label stay (2.*)?

**Comment by som-snytt** [comment]
It needs a label `revertible` to mean the behavior change was specific to a commit, while reserving `regression` for "specified" or "guaranteed" behaviors which changed in a release but need not be specific to a commit (or PR).

In addition, of course, having a workaround (of some sort) mitigates the need for a fix (which may cause revertible effects in turn).

And perhaps a more optimal fix will be forthcoming than could be achieved by the next release. A regression has an urgency attached to it that drags upon any alleviation. "Haste makes waste."

**Comment by abebeos** [comment]
> It needs a label `revertible` [...]

`regression` is fine (and its standard-procedure/terminology)

@som-snytt , may I ask what your role is within this project?

**Comment by som-snytt** [comment]
@abebeos I was suggesting why "regression" is not appropriate. You may disagree, of course. Such is the open in open source.

**Comment by abebeos** [comment]
> open

You're misinterpreting "openness" with "freedom to make distracting quasi-philosophical comments re procedure and terminology". I'm awaiting the reply of @lrytz, the relevant authority for the issue at hand.

**Comment by abebeos** [comment]
> @som-snytt , may I ask what your role is within this project?

answering myself: long-term contributor, rank 5, https://github.com/scala/scala/graphs/contributors

(...and long-term contributors have of course the right to break now and then the "protocoll", including posting quasi-philosophical off-topics)

Back to topic/issue:

The queston is if https://github.com/scala/scala/pull/10247 did actually introduce "expected behaviour", and not "a regression", e.g. the canonical example within https://github.com/scala/bug/issues/12814#issuecomment-1822770100 needs `-Yrecursion 1` to compile successfully, and so does the reproducer of this issue.

More info (including the initial commit re `Yrecursion` https://github.com/scala/scala/commit/fa8d0d8d853cebdfa33552ca2f66c229b6d39f2d) within:

- https://github.com/scala/bug/issues/12911

**Comment by som-snytt** [comment]
@abebeos there is no such protocol. I was trying to answer your question so Lukas wouldn't have to. You are free to be dissatisfied with my answer on its merits, of course. Either Lukas made a mistake in removing the regression label, or he was not mistaken but you are asking to prioritize this issue.

**Comment by abebeos** [comment]
> Canonical example:

lrytz, note that your example fiails on both, 2.13.11 and 2.13.10, and thus it looks like it is not related to the problem/code mentioned by the OP (that workds on 2.13.10, but fails on 2.13.11).

Please verify your example/conclusions.

**Comment by lrytz** [comment]
It's the canonical example in the sense that it shows the underlying problem, which indeed has been around for a long time (also 2.12).

My example fails in the type checking phase. The example given in this ticket fails in a later phase (patmat) which generates code similar to my example and then fails to type check it. So the change in patmat (https://github.com/scala/scala/pull/10247) exposed the underlying issue in a new way, it did not cause it. That's why I removed the "regression" label, but one can argue either way.

**Comment by lrytz** [comment]
It seems @retronym has a branch for it: https://github.com/scala/bug/issues/8252#issuecomment-535264336 (haven't looked, but it seems that).

**Comment by abebeos** [comment]
> It seems @retronym has a branch for it: [#8252 (comment)](https://github.com/scala/bug/issues/8252#issuecomment-535264336) (haven't looked, but it seems that).

Quickly reviewed, this seems to me like reimplementing (parts of) `-Yrecursion` functionality. 

https://github.com/scala/scala/blob/fa8d0d8d853cebdfa33552ca2f66c229b6d39f2d/src/compiler/scala/tools/nsc/symtab/Symbols.scala#L32-L33

Would be possibly easier/better to say:

"There is a know issue with 'cyclic aliasing or subtyping', that can be solved by using `-Yrecursion:n`, where `n` is the type-hierarchy level you need" (something like that).
