### ISSUE TITLE
scala 2.12.4 Accessing Java protected static field from class in different package does not compile

### ISSUE THREAD

**Issue by lhohan** [scala/bug#10597]
Hi,

When upgrading to 2.12.4 we encounted a compilation issue which seems to be regression.

It seems one cannot access an inherited protected field in a Java class in a different package then the one the deriving class is in.

Compilation succeeds when both classes are in the same package.

This issue might be related to: 
https://github.com/scala/scala/pull/6058
https://github.com/scala/bug/issues/10568

Code:

Handler.java
```
package a;

public abstract class Handler {
  protected static final String CONST = "abc123";
}
```

HandlerImpl.java
```
import a.Handler
import a.Handler.CONST

class HandlerImpl extends Handler {
  
  def doSomethingWithConst: String = {
    CONST
  }

}
```

Output using `sbt`:

```
$ java -version                                                                         
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

$ sbt

sbt> show scalaVersion
[info] 2.12.4

sbt> ;clean;compile
[success] Total time: 0 s, completed Nov 7, 2017 8:18:10 PM
[info] Compiling 1 Scala source and 1 Java source to /Users/hho/dev/scala_2.12.4_bug/target/scala-2.12/classes ...
[error] /Users/hho/dev/scala_2.12.4_bug/src/main/scala/HandlerImpl.scala:7:5: not found: value CONST
[error]     CONST
[error]     ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 3 s, completed Nov 7, 2017 8:18:13 PM

sbt> set scalaVersion := "2.12.3"

sbt> show scalaVersion
[info] 2.12.3

sbt> ;clean;compile
[success] Total time: 0 s, completed Nov 7, 2017 8:18:29 PM
[info] Updating {file:/Users/hho/dev/scala_2.12.4_bug/}scala_2-12-4_bug...
[info] Done updating.
[info] Compiling 1 Scala source and 1 Java source to /Users/hho/dev/scala_2.12.4_bug/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 2 s, completed Nov 7, 2017 8:18:31 PM
```

I created a gist here: https://gist.github.com/lhohan/c7e8096c3486c6d810283d4753049c4a

**Comment by lukaseder** [comment]
Seems like a rather critical regression for interoperating code...

**Comment by lukaseder** [comment]
Seems like a duplicate of https://github.com/scala/bug/issues/10568 (thanks @er1c for digging this out)
