### ISSUE TITLE
Failed to generate Scaladoc when Java sources involve a raw type (worked in 2.12.10, regressed in 2.12.11)

### ISSUE THREAD

**Issue by wangyum** [scala/bug#11917]
## reproduction steps
```shell
git clone https://github.com/apache/spark.git
cd spark
build/mvn clean  install -DskipTests=true -Phive-thriftserver -pl sql/hive-thriftserver  -Dscala.version=2.12.11
```

## problem

```java
[INFO] --- scala-maven-plugin:4.3.1:doc-jar (attach-scaladocs) @ spark-hive-thriftserver_2.12 ---
/Users/yumwang/spark/sql/hive-thriftserver/v2.3/src/gen/java/org/apache/hive/service/rpc/thrift/TCLIService.java:660: error: class type required but org.apache.thrift.async.TAsyncMethodCall[_] found
    public static class OpenSession_call extends org.apache.thrift.async.TAsyncMethodCall {
                                                                         ^
/Users/yumwang/spark/sql/hive-thriftserver/v2.3/src/gen/java/org/apache/hive/service/rpc/thrift/TCLIService.java:692: error: class type required but org.apache.thrift.async.TAsyncMethodCall[_] found
    public static class CloseSession_call extends org.apache.thrift.async.TAsyncMethodCall {
                                                                          ^
/Users/yumwang/spark/sql/hive-thriftserver/v2.3/src/gen/java/org/apache/hive/service/rpc/thrift/TCLIService.java:724: error: class type required but org.apache.thrift.async.TAsyncMethodCall[_] found
 
...
```

More details:
https://github.com/apache/spark/pull/27929/checks?check_run_id=521333701

**Comment by SethTisue** [comment]
is it reproducible in a small, self-contained test case?

looks like a problem with raw types

you say "java doc", do you mean Scaladoc?

**Comment by xuwei-k** [comment]
### A.java 

```java
package foo;

public class A<B> {}
```

### X.java 

```java
package foo;

public class X extends A {}
```

### Z.scala 

```scala
package bar

class Z
```


### build.properties

```
sbt.version=1.3.8
```

### build.sbt

```scala
scalaVersion := "2.12.11"
```


### `sbt doc` output

```
X.java:3:24: class type required but foo.A[_] found
[error] public class X extends A {}
[error]                        ^
[info] No documentation generated with unsuccessful compiler run
[error] one error found
[error] (Compile / doc) Scaladoc generation failed
```

**Comment by eed3si9n** [comment]
@xuwei-k Thanks!

**Comment by lrytz** [comment]
> do you mean Scaladoc? (or are you using genjavadoc?)

scaladoc only, after @xuwei-k's example

**Comment by hrhino** [comment]
I think I broke this one.
