### ISSUE TITLE
Implicit conversion into a dependent type is not found

### ISSUE THREAD

**Issue by neko-kai** [scala/bug#11791]
### Example:

```scala
trait X1[A] {
  def x1: A => A
}
object X1 {
  implicit def X2[A]: X2[A] = new X2[A] {
    override def x2: A => A = identity
    override def x1: A => A = identity
  }
}

trait X2[A] extends X1[A] {
  def x2: A => A
}

object X {
  implicit def toX12[A](self: X.type)(implicit x: X1[A]): x.type = x
}

object example extends App {
  def x1[A: X1](a: A) = {
    X.x1(a)
  }
  def x2[A: X2](a: A) = {
    X.x2(a)
  }
  println(x1(2))
}
```

### Expected:
`X.x2(a)` call to compile, but got an error message:

```
Error:(26, 7) value x2 is not a member of object X
    X.x2(a)
```

Note that the example works in dotty 0.20 as expected: https://scastie.scala-lang.org/Tusgmci0Toau5WI58FSZTQ

### Workaround:

Explicitly listing creating prioritized conversions for all subtypes of `X1`:

```scala
object X extends LowPriorityX {
  implicit def toX1[A](self: X.type)(implicit x: X1[A]): X1[A] = x
}
trait LowPriorityX {
  implicit def toX2[A](self: X.type)(implicit x: X2[A]): X2[A] = x
}
```
