### ISSUE TITLE
Spurious access error typechecking java sources with protected inner class

### ISSUE THREAD

**Issue by retronym** [scala/bug#12673]
## Reproduction steps

Scala version: 2.13.10

```java
package compiletest.a;
public class OuterParent {
    protected static class InnerParent {
    }
}
```

```java
package compiletest.b;
import compiletest.a.OuterParent;

public class OuterChild extends OuterParent {
    public static class InnerChild extends InnerParent {
    }
}
```

```scala
package client

object Client {
  new compiletest.b.OuterChild.InnerChild
}
```

## Problem

When the files are compiled jointly, scalac emits a spurious error:

```
➜ scalac --scala-version 2.13.10 -d /tmp -cp /tmp test/files/pos/java-protected-inner-static-class-ypicklejava/*
test/files/pos/java-protected-inner-static-class-ypicklejava/OuterChild.java:5: error: class InnerParent in class OuterParent cannot be accessed as a member of object compiletest.b.OuterChild from class OuterChild in package b
 Access to protected class InnerParent not permitted because
 enclosing class OuterChild in package b is not a subclass of
 class OuterParent in package a where target is defined
    public static class InnerChild extends InnerParent {
                                           ^
1 error
```

Workaround is to compile separately:

```
➜ javac -d /tmp test/files/pos/java-protected-inner-static-class-ypicklejava/*.java
➜ scalac --scala-version 2.13.10 -d /tmp -cp /tmp test/files/pos/java-protected-inner-static-class-ypicklejava/*.scala
```
