### ISSUE TITLE
implicit resolution issue when using tagged types

### ISSUE THREAD

**Issue by fommil** [scala/bug#10954]
Without copying an implementation of scalaz tagged types into this example, this is as minimal as I can get this compilation failure.

Removing the `//` comments, this compiles, which shouldn't intuitively be needed because the instance is on the companion of `Bar`. 

However, it is unclear if the companion of `Bar` should even be searched. It is certainly a parameter of the type, so I would have thought it should be. A fine grained interpretation of the SLS is needed here.

Incidentally, @jdegoes, this will be worked around by `scalaz-zio` because the instance for `Bar` (i.e. `IO`) will be on `Foo` (i.e. `Applicative`), which is certainly in the implicit search.

// @hrhino

```scala
import scalaz.@@
import scalaz.Tags.Parallel

trait Foo[F[_]]
object Foo {
  @inline def apply[F[_]](implicit F: Foo[F]): Foo[F] = F
}

class Bar[A]
object Bar {
  implicit def foo: Foo[λ[α => Bar[α] @@ Parallel]] = ???
}

object Main {
  //implicit val hack = Bar.foo (or import)
  Foo[λ[α => Bar[α] @@ Parallel]]
}
```

**Comment by hrhino** [comment]
Thanks for the minimization. I'm of the opinion that this should compile, too. I'll go read the spec tonight or tomorrow and post a formal argument for why. 

Just to double check, this fails on 2.12.6? (I'd check but I'm on my phone for the next few hours).

**Comment by fommil** [comment]
nope

```
[error] bug.scala:21:6: could not find implicit value for parameter F: bug.Foo[[α]Object{type Tag = scalaz.Tags.Parallel; type Self = bug.Bar[α]}]
[error]   Foo[λ[α => Bar[α] @@ Parallel]]
[error]      ^

```

**Comment by SethTisue** [comment]
if this works in 2.13.0-M4, we should close the ticket. does it?

**Comment by fommil** [comment]
I am not using 2.13 at work and will not be doing so for a long time. Is there a reason to believe that this is fixed in 2.13?

**Comment by hrhino** [comment]
Nope.

```scala
hhoughton:tmp hhoughton$ cat fommil.scala
import scalaz.@@
import scalaz.Tags.Parallel

trait Foo[F[_]]
object Foo {
  @inline def apply[F[_]](implicit F: Foo[F]): Foo[F] = F
}

class Bar[A]
object Bar {
  implicit def foo: Foo[({ type λ[α] = Bar[α] @@ Parallel })#λ] = ???
}

object Main {
  //implicit val hack = Bar.foo (or import)
  Foo[({ type λ[α] = Bar[α] @@ Parallel })#λ]
}
hhoughton:tmp hhoughton$ scalac-launch 2.13.0-M4 -cp `coursier fetch -p org.scalaz:scalaz-core_2.13.0-M4:7.2.24` fommil.scala
fommil.scala:16: error: could not find implicit value for parameter F: Foo[[α]Object{type Tag = scalaz.Tags.Parallel; type Self = Bar[α]}]
  Foo[({ type λ[α] = Bar[α] @@ Parallel })#λ]
     ^
one error found
hhoughton:tmp hhoughton$
```

What's going on is that by the time implicit search happens, the type lambda's been normalized to `AnyRef { type Self = Bar[α] ; type Tag = Parallel }`, and the only parts of that type are `AnyRef` and its parts. The spec doesn't appear to mandate this dealiasing, so I'd say this is probably a bug in that sense.

I think this is a major weakness of scalaz 7.2's tagged types encoding, and I'm not sure why it was done this way. The scalaz 7.3 encoding has no issues here; nor does defining it as simply `object Tags { type @@[A, Tag] }`.

**Comment by SethTisue** [comment]
seems peculiar it would work in 2.12 with `-Xsource:2.13` but fail in actual 2.13

**Comment by hrhino** [comment]
@SethTisue no, sorry about that, it fails in 2.12, too. As I brought up on gitter, I tried to reproduce without scalaz by inlining the definition of `@@`, but I forgot what it actually was.

scalaz 7.2 has:
```scala
package object scalaz {
  /* ... */
  private[scalaz] type Tagged[A, T] = { type Self = A ; type Tag = T }
  type @@[A, T] = Tagged[A, T]
}
```

I used:
```scala
object scalaz {
  type @@[A, T]
}
```

It works with the latter encoding but not with the former. I haven't managed to find what about the former is superior; it leads to this problem where the implicit search considers only the parts of `AnyRef { type Self = A; type Tag = T }`, rather than of the (non-dealiased) `A @@ T`.

**Comment by adriaanm** [comment]
Nice analysis, @hrhino! The `@@` alias is expanded and the parts of a structural type do not include its members. 

The spec is ambiguous on the expansion of a type application to a type alias. (See https://www.scala-lang.org/files/archive/spec/2.12/07-implicits.html#implicit-parameters -- I've included the relevant cases of the definition below.)

The _parts_ of a type T are:

- if T is a compound type `T_1 with ... with T_n`,  the union of the parts of T_1 , ... , T_n, as well as T itself;
- if T is a parameterized type `S[T_1 , ... , T_n]`,  the union of the parts of S and T_1 , ... , T_n;
- if T is a type projection `S#U`,  the parts of S as well as T itself;
- if T is a type alias, the parts of its expansion;
- if T is an abstract type, the parts of its upper bound;
- in all other cases, just T itself.

I think the ambiguity stems from assuming type applications can only involve classes (ignoring type constructor polymorphism). At least, this is how it's implemented.

Self-contained test:
```scala
object scalaz {
  trait Parallel
  type @@[A, T] = { type Self = A ; type Tag = T }
}
import scalaz._


trait Foo[F[_]]

class Bar[A]
object Bar {
  implicit def foo: Foo[({ type λ[α] = Bar[α] @@ Parallel })#λ] = ???
}

object Main {
  // import Bar.foo -- Bar is not in the implicit scope because it's not in the parts of `@@[Bar[α], Parallel]`
  implicitly[Foo[({ type λ[α] = Bar[α] @@ Parallel })#λ]]
}
```

I don't understand the definition of `@@` in scalaz. Privacy is not taken into account for type alias expansion, so the extra ceremony doesn't amount to anything I can think of. If you made `@@` a trait, it would work: `trait @@[A, T] { type Self = A ; type Tag = T }`.

**Comment by fommil** [comment]
@adriaanm thanks, so are we saying this is a bug or not a bug?

If you want more details on anything related to scalaz, you could ask your colleague, Jason, as he is [the primary author](https://github.com/scalaz/scalaz/graphs/contributors?from=2008-11-30&to=2018-06-26&type=a)  :smile: 

Changing the definition of `@@` is not an option: it is an upstream dependency. As @hrhino points out though, it is changed in scalaz7.3.

**Comment by adriaanm** [comment]
I was looking at the dotty implementation, and it looks like they interpret the spec to include any type application. So, we should as well. I'll consider this change for M5, assuming it doesn't cause any regressions. I hesitate a bit, because I'm not keen on enlarging the implicit scope, but it does feel more intuitive.

**Comment by adriaanm** [comment]
(See https://github.com/scala/scala-dev/issues/446 re: my unease.)

**Comment by hrhino** [comment]
Independently of whether this is a bug, and independently of whether this can be fixed, I think the current scalaz encoding is (as Adriaan points out) much ceremony for nothing, and it's good that it's getting changed in 7.3. @fommil what do you think would be wrong with changing the 7.2 definition to

```scala
type @@[A, T] <: { type Tag = T ; type Self = A }
```

which should IIUC make this work.

**Comment by joroKr21** [comment]
`@@` got dealiased before implicit search because of the hacky encoding of type lambdas (`({ type λ[α] = Bar[α] @@ Parallel })#λ`). `λ` here has to be dealiased to figure out what it is and there is no partial dealiasing.

**Comment by fommil** [comment]
@hrhino you'd be best talking to kenji and stephen compall about that. It sounds like it might have far reaching consequences, so maybe best left for 7.3.

**Comment by retronym** [comment]
[Previous discussion](https://github.com/scala/bug/issues/9770#issuecomment-292440679) about the can-of-worms that gets opened when considering the arguments of alias applications. (e.g. should we do this for each step of dealising?).

I borrowed the formulation of `@@` in Scalaz from @milessabin, IIRC. I didn't consider the interaction with the implicit scope.
