### ISSUE TITLE
Implicits fails when solving LUB on kinded types

### ISSUE THREAD

**Issue by ayvango** [scala/bug#10789]
I tried to compute least upper bound with two different ways. Implicit way fails with kinded types but works fine with concrete types

```scala
object Direct {
  final case class H[T]() {
    def lub[U >: T, O <: U](other : H[O]) = H[U]()
  }
  final case class K[T]()

  H[Int]() lub H[Boolean]() lub H[String]() // works
  H[K[Int]]() lub H[K[Boolean]] lub H[K[String]] // works too
}

object Implicit {
  sealed trait Solver[L, R] {
    type Common
  }
  implicit def trivialSolver[U, L <: U, R <: U] = new Solver[L,R] {
    override type Common = U
  }

  final case class H[T]() {
    def lub[O](other : H[O])(implicit solve : Solver[T, O]) : H[solve.Common] = H[solve.Common]()
  }
  final case class K[T]()

  H[Int]() lub H[Boolean]() lub H[String]() // works
  H[K[Int]]() lub H[K[Boolean]] lub H[K[String]] // fails
}
```

the error message:
```
HKTLUB.scala:25: error: could not find implicit value for parameter solve: Implicit.Solver[Implicit.K[_ >: Boolean with Int <: AnyVal],Implicit.K[String]]
  H[K[Int]]() lub H[K[Boolean]] lub H[K[String]] // fails
                                ^
one error found
```

the compiler version is
>  Scala compiler version 2.11.11-20160304-000000-1706a37eb8 -- Copyright 2002-2017, LAMP/EPFL

**Comment by joroKr21** [comment]
Did you try the latest version? It works on 2.12.4

**Comment by ayvango** [comment]
It is working indeed. Shouldn't the bug be marked as duplicate to some other bug already fixed?

**Comment by SethTisue** [comment]
@ayvango yes, please do comment here with an original ticket number if you can find one. (the volume of reports in scala/bug is high, so tasks like this are crowdsourced.)
