### ISSUE TITLE
-Xexperimental dependent types regression

### ISSUE THREAD

**Issue by scabug** [scala/bug#4518]
=== What steps will reproduce the problem (please be specific and use wikiformatting)? ===
scalac -Xexperimental Broke.scala 
```scala
class Broke {

  val tempval = new AnyRef {val roleA = new AnyRef with Bar}.roleA

  new AnyRef {} -: tempval // when not assigning to anything, no problem
  val broke_val = new AnyRef {} -: tempval // type mismatch error only when assigning

  trait Foo[AnyRef] {  }

  trait Bar extends Foo[AnyRef] {
    def -:(core: AnyRef): this.type with Foo[core.type] = throw new Exception()
  }
} 
```

=== What is the expected behavior? ===
Compiles without error, as it did with 2.7.7 and 2.8.1

=== What do you see instead? ===
Broke.scala:6: error: type mismatch;
 found   : Broke.this.tempval.type with Broke.this.Foo[x$$2.type(in value broke_val)] where type x$$2.type(in value broke_val) <: java.lang.Object with Singleton
 required: Broke.this.tempval.type with Broke.this.Foo[x$$2.type(in value broke_val)] forSome { type x$$2.type(in value broke_val) <: java.lang.Object with Singleton }
  val broke_val = new AnyRef {} -: tempval // type mismatch error only when assigning
      ^
one error found

=== Additional information ===
(for instance, a link to a relevant mailing list discussion)

=== What versions of the following are you using? ===
  - Scala: 2.9RC1
  - Java: n/a
  - Operating system: Debian Linux sid

**Comment by som-snytt** [comment]
It wasn't fixed under the linked ticket after all.

**Comment by magnolia-k** [comment]
The code in this example can be compiled.

Also, the `-Xexperimental` option has been deprecated since Scala 2.13.0, so the issue itself can be closed.

**Comment by som-snytt** [comment]
It is added as a pos test in the linked PR, which may make it into 2.13.7. Presumably it did not compile on pre-release 2.13.

**Comment by som-snytt** [comment]
It's the Adriaan reduction that fails. That is because rassoc rewrite extracts the expression in parser, so some context is lost; the linked PR rewrites in typer.

**Comment by SethTisue** [comment]
@som-snytt (care to revise the issue title? the current title attracted my attention since `-Xexperimental` no longer exists)

**Comment by som-snytt** [comment]
I'm glad I left a few breadcrumbs for future self. Here's Adriaan's reduction again:
```
object Test {
  trait Foo[T]

  trait Bar {
    def -:(core: AnyRef): Foo[core.type] = error("")
  }

  val tempval: Bar = error("")
  val cor: AnyRef = error("")

  val ok : Foo[cor.type] = tempval.-:(cor)
  val oops : Foo[cor.type] = cor -: tempval

  def error(s: String) = ???
}
```
currently 2.13.12
```
t4518b.scala:13: error: type mismatch;
 found   : Test.Foo[rassoc$1.type]
 required: Test.Foo[Test.cor.type]
  val oops : Foo[cor.type] = cor -: tempval
                                 ^
1 error
```
I see that is a pos test on my branch but not yet pushed to the PR. I will need to catch up because
```
On branch issue/5073-rassoc-method-value
Your branch and 'upstream/2.13.x' have diverged,
and have 1 and 1014 different commits each, respectively.
```
oh man, that's sbt 1.8.2, I have to downgrade my jdk.

OK, it compiles on that branch. I suspect Lukas was just giving me a hard time on the last mile. It will take me a bit to rebase because I'm starting season 2 of Dawson's Creek, they're literally still kissing. I think cliffhanger is specialized lingo for whatever generation that is.

**Comment by som-snytt** [comment]
I can't improve on Adriaan's description, except one tweak for length.
