### ISSUE TITLE
Erasure of tasty method with ValueOf[Int with Singleton] param

### ISSUE THREAD

**Issue by bishabosha** [scala/bug#12259]
a method with a parameter of type `ValueOf[I]` where `I <: Int` will erase to `java.lang.Integer` and not `java.lang.Object` as the descriptor of `Values.reify` requires
## reproduction steps

using Scala (2.13.4),

```scala
// compile with Scala 3.0.0-M2
object Values {
  def reify[I <: Int](implicit I: ValueOf[I]): I = valueOf[I]
}
```

```scala
// compile with Scala 2.13.4
object Test extends App {
  println(Values.reify[3])
}
```

## problem

runtime error:
```scala
[error] Test scala.tools.tastytest.TastyTestJUnit.run failed: java.lang.NoSuchMethodError: tastytest.Values$.reify(Ljava/lang/Integer;)I, took 18.115 sec
[error]     at tastytest.TestValues$.$anonfun$new$1(TestValues.scala:8)
[error]     at tastytest.Suite.$anonfun$runImpl$2(Suite.scala:49)
[error]     at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]     at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error]     at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
[error]     at tastytest.Suite.runImpl(Suite.scala:48)
[error]     at tastytest.Suite.main(Suite.scala:40)
[error]     at tastytest.TestValues.main(TestValues.scala)
```

**Comment by bishabosha** [comment]
I believe this is actually an issue on the dotty side, the descriptor for `Values.reify` is `(Ljava/lang/Object;)I` but in scala 2 would be `(Ljava/lang/Integer;)I`

**Comment by smarter** [comment]
This should be fixed by https://github.com/lampepfl/dotty/pull/10765.
