### ISSUE TITLE
ScalaDoc 2.12.3 fails on simple Java class with static Enum/Class in constructor

### ISSUE THREAD

**Issue by bantonsson** [scala/bug#10509]
This simple file `Broken.java`

```java
public class Broken {
    public enum Should {
        Foo
    }

    public static class Work {
    }

    public Broken(Should should, Work work) {
    }
}
```

Will fail like this

```
> scaladoc Broken.java
Broken.java:9: error: not found: type Should
    public Broken(Should should, Work work) {
                  ^
Broken.java:9: error: not found: type Work
    public Broken(Should should, Work work) {
                                 ^
model contains 2 documentable templates
two errors found
```

Works with ScalaDoc 2.11.11

**Comment by SethTisue** [comment]
in 2.11, Scaladoc didn't process Java sources at all, so I don't think this is a regression?

**Comment by SethTisue** [comment]
workaround:

```
-    public Broken(Should should, Work work) {
+    public Broken(Broken.Should should, Broken.Work work) {
```

related: #1211

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/8993 et al
