### ISSUE TITLE
 2.13 regression: variable-binding pattern doesn't work for case objects in some cases

### ISSUE THREAD

**Issue by nehaev** [scala/bug#11574]
The following code works fine on Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_212):

```scala
trait T
case object A extends T
  
val x: Any = A
  
def p(t: T) = println("T: $t")
  
x match {
  case a@A => p(a)
  case unk => println(s"Unk: $unk")
}
```

On Scala 2.13.0 this code produces a compilation error:

```
[error] /TestApp.scala:14:17: type mismatch;
[error]  found   : Any
[error]  required: TestApp.T
[error]   case a@A => p(a)
[error]                 ^
```

**Comment by som-snytt** [comment]
`-Xlint` reports:
```
$ ~/scala-2.12.8/bin/scalac -Xlint objpat.scala
objpat.scala:10: warning: possible missing interpolator: detected interpolated identifier `$t`
  def p(t: T) = println("T: $t")
                        ^
objpat.scala:14: warning: The value matched by A is bound to a, which may be used under the
unsound assumption that it has type objpat.A.type, whereas we can only safely
count on it having type Any, as the pattern is matched using `==` (see scala/bug#1503).
      case a@A => p(a)
             ^
```
Per the second warning, for your expectation, use
```
case a: A.type => p(a)
```
which is enforced now. Under 2.12, you would see this behavior under `-Xfuture`.

**Comment by nehaev** [comment]
Thank you for the clarification, @som-snytt!
