### ISSUE TITLE
Reference to Jersey RxClient[RxListenableFutureInvoker] fails to compile

### ISSUE THREAD

**Issue by dsilvasc** [scala/bug#10618]
Hi, I'm trying to migrate some java code using the jersey rest client RxListenableFutureInvoker but scala has trouble compiling it on both 2.11 and 2.12.

Reproducible on the Ammonite repl:

```
Welcome to the Ammonite Repl 1.0.2
(Scala 2.12.3 Java 1.8.0_144)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`org.glassfish.jersey.core:jersey-common:2.22.1`
@ import $ivy.`org.glassfish.jersey.core:jersey-client:2.22.1`
@ import $ivy.`com.google.guava:guava:19.0-rc2`
@ import $ivy.`org.glassfish.jersey.ext.rx:jersey-rx-client-guava:2.22.1`
@ import org.glassfish.jersey.client.rx.RxClient
@ import org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker
@ import javax.ws.rs.client.ClientBuilder
@ import org.glassfish.jersey.client.rx.guava.RxListenableFuture
@ val client = ClientBuilder.newClient()
client: Client = org.glassfish.jersey.client.JerseyClient@43e67511
@ val rc = RxListenableFuture.from(client)
cmd19.sc:1: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
val rc = RxListenableFuture.from(client)
    ^
cmd19.sc:8: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
            .print(rc, "rc", _root_.scala.None)
             ^
cmd19.sc:8: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
            .print(rc, "rc", _root_.scala.None)
                  ^
Compilation Failed
```

Writing down the type also fails to compile:

```
@ var rc: RxClient[RxListenableFutureInvoker] = null
cmd19.sc:1: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
var rc: RxClient[RxListenableFutureInvoker] = null
        ^
cmd19.sc:8: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
            .print(rc, "rc", _root_.scala.None)
             ^
cmd19.sc:8: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
            .print(rc, "rc", _root_.scala.None)
                  ^
Compilation Failed
```

The equivalent java `RxClient<RxListenableFutureInvoker> rxclient` compiles fine in javac 1.7.

**Comment by dsilvasc** [comment]
Jersey documentation: https://jersey.github.io/documentation/2.22.1/rx-client.html#rx-client.guava

See "Example 6.14. Creating Jersey/Guava Client and WebTarget – Using RxListenableFuture" -- this fails to compile as well.

```
@ RxListenableFuture.newClient()
cmd20.sc:1: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
val res20 = RxListenableFuture.newClient()
    ^
cmd20.sc:8: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
            .print(res20, "res20", _root_.scala.None)
             ^
cmd20.sc:8: type arguments [org.glassfish.jersey.client.rx.guava.RxListenableFutureInvoker] do not conform to trait RxClient's type parameter bounds [RX <: org.glassfish.jersey.client.rx.RxInvoker[_]]
            .print(res20, "res20", _root_.scala.None)
                  ^
Compilation Failed
```
