### ISSUE TITLE
Regression 2.13: implicit resolution and partial unification

### ISSUE THREAD

**Issue by japgolly** [scala/bug#11765]
The following code works in 2.12.x but fails to compile on 2.13.1:

```scala
object Blah {

  trait TC[F[_]]

  final class Ops[F[_], A](m: F[A])(implicit p: TC[F]) {
    def example = 0
  }

  implicit def toTcOps[F[_], A](fa: F[A])(implicit tc: TC[F]): Ops[F, A] =
    new Ops[F, A](fa)(tc)

  final case class X[A]()

  implicit val tcX: TC[X] =
    new TC[X] {}

  object Example1 {
    type Y[A, B] = X[(A, B)] // both arguments used

    def woah[A, B](a: Y[A, B]) = {
      a.example                      // Error in 2.13 but ok in 2.12
      toTcOps(a).example             // Error in 2.13 but ok in 2.12
      toTcOps[X, (A, B)](a).example  // OK in 2.13 & 2.12
    }
  }

  object Example2 {
    type Y[A, B] = X[A] // phantom type

    def woah[A, B](a: Y[A, B]) = {
      a.example                 // Error in 2.13 but ok in 2.12
      toTcOps(a).example        // Error in 2.13 but ok in 2.12
      toTcOps[X, A](a).example  // OK in 2.13 & 2.12
    }
  }

}
```

Error:

```
[error] Blah.scala:21:9: value example is not a member of Blah.Example1.Y[A,B]
[error]       a.example                 // Error in 2.13 but ok in 2.12
[error]         ^
[error] Blah.scala:22:14: could not find implicit value for parameter tc: Blah.TC[[B]Blah.Example1.Y[A,B]]
[error]       toTcOps(a).example        // Error in 2.13 but ok in 2.12
[error]              ^
[error] Blah.scala:31:9: value example is not a member of Blah.Example2.Y[A,B]
[error]       a.example                 // Error in 2.13 but ok in 2.12
[error]         ^
[error] Blah.scala:32:14: could not find implicit value for parameter tc: Blah.TC[[B]Blah.Example2.Y[A,B]]
[error]       toTcOps(a).example        // Error in 2.13 but ok in 2.12
[error]              ^
[error] four errors found

```

**Comment by joroKr21** [comment]
The examples also fail on 2.12.10 with `-Ypartial-unification` which is unconditional in 2.13

**Comment by japgolly** [comment]
Thanks @joroKr21 , I forgot to mention that I have `-Ypartial-unification` on for 2.12 :grin:

**Comment by japgolly** [comment]
Hmm I just tried with on 2.12.10 *without* `-Ypartial-unification` and it compiles.

```
> scala  
Welcome to Scala 2.12.10 (OpenJDK 64-Bit GraalVM CE 19.2.0, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> object Blah {
     | 
     |   trait TC[F[_]]
     | 
     |   final class Ops[F[_], A](m: F[A])(implicit p: TC[F]) {
     |     def example = 0
     |   }
     | 
     |   implicit def toTcOps[F[_], A](fa: F[A])(implicit tc: TC[F]): Ops[F, A] =
     |     new Ops[F, A](fa)(tc)
     | 
     |   final case class X[A]()
     | 
     |   implicit val tcX: TC[X] =
     |     new TC[X] {}
     | 
     |   object Example1 {
     |     type Y[A, B] = X[(A, B)] // both arguments used
     | 
     |     def woah[A, B](a: Y[A, B]) = {
     |       a.example                      // Error in 2.13 but ok in 2.12
     |       toTcOps(a).example             // Error in 2.13 but ok in 2.12
     |       toTcOps[X, (A, B)](a).example  // OK in 2.13 & 2.12
     |     }
     |   }
     | 
     |   object Example2 {
     |     type Y[A, B] = X[A] // phantom type
     | 
     |     def woah[A, B](a: Y[A, B]) = {
     |       a.example                 // Error in 2.13 but ok in 2.12
     |       toTcOps(a).example        // Error in 2.13 but ok in 2.12
     |       toTcOps[X, A](a).example  // OK in 2.13 & 2.12
     |     }
     |   }
     | 
     | }
<console>:13: warning: higher-kinded type should be enabled
by making the implicit value scala.language.higherKinds visible.
This can be achieved by adding the import clause 'import scala.language.higherKinds'
or by setting the compiler option -language:higherKinds.
See the Scaladoc for value scala.language.higherKinds for a discussion
why the feature should be explicitly enabled.
         trait TC[F[_]]
                  ^
<console>:15: warning: higher-kinded type should be enabled
by making the implicit value scala.language.higherKinds visible.
         final class Ops[F[_], A](m: F[A])(implicit p: TC[F]) {
                         ^
<console>:19: warning: higher-kinded type should be enabled
by making the implicit value scala.language.higherKinds visible.
         implicit def toTcOps[F[_], A](fa: F[A])(implicit tc: TC[F]): Ops[F, A] =
                              ^
<console>:19: warning: implicit conversion method toTcOps should be enabled
by making the implicit value scala.language.implicitConversions visible.
This can be achieved by adding the import clause 'import scala.language.implicitConversions'
or by setting the compiler option -language:implicitConversions.
See the Scaladoc for value scala.language.implicitConversions for a discussion
why the feature should be explicitly enabled.
         implicit def toTcOps[F[_], A](fa: F[A])(implicit tc: TC[F]): Ops[F, A] =
                      ^
defined object Blah
```

**Comment by japgolly** [comment]
I also tried it on the following and it compiles successfully without `-Ypartial-unification`:
* 2.12.2
* 2.12.3
* 2.12.4
* 2.12.8
* 2.12.10

**Comment by joroKr21** [comment]
Yes I meant that it fails with `-Ypartial-unification` **on**, i.e. it's ther result of partial unifcation.
Because the compiler will accept `Y[A, *]` instead of searching in the supertypes and finding `X`.

**Comment by SethTisue** [comment]
@milessabin ring a bell?

**Comment by milessabin** [comment]
I think that @joroKr21 has diagnosed the issue.

**Comment by japgolly** [comment]
Hi. Is someone able to tag this with the `regression` label? It seems I don't have access to.

**Comment by japgolly** [comment]
(Thanks @lrytz)

**Comment by japgolly** [comment]
This is issue is a huge blocker to me because it completely prevents downstream usage of
https://github.com/japgolly/test-state

Is there something I can do to get this resolved for 2.13.2?
I'd be happy to even try my hand at a PR to resolve but if someone's able to maybe help guide me...? I'm afraid I don't know the compiler internals very well at all. Please let me know how I can help. Cheers.

**Comment by joroKr21** [comment]
But that's just how partial unification works. The only "fix" I can think of is to make implicit search influence unification but I don't know if that's feasible or desirable.

**Comment by japgolly** [comment]
All I'm doing is adding extension methods to a F[_] given a TC[F]. If we're saying it works for F[Int] but not F[(Int, Int)] then it's broken for general usage. You can't release a library and tell users to only use the simplest types. Surely we don't want to lose that general ability in Scala itself.

**Comment by japgolly** [comment]
Ooooooh, I probably knew that when I provided a minification but I'd definitely forgotten that.

Ok now I think I understand your other comment about feasibility & desirability. Sorry if this is naive, but wouldn't it just be a case of dealising and trying again the implicit search again when it fails on a type alias?

**Comment by joroKr21** [comment]
That's a good question. I think by the time we try implicit search the types are already inferred as determined by `F[A]`. Dotty has the same problem (but better error message):
```
21 |      a.example                      // Error in 2.13 but ok in 2.12
   |      ^^^^^^^^^
   |      value example is not a member of Blah.Example1.Y[A, B].
   |      An extension method was tried, but could not be fully constructed:
   |
   |          Blah.toTcOps[([B] => Blah.Example1.Y[A, B]), B](a)(tcX)
22 |      toTcOps(a).example             // Error in 2.13 but ok in 2.12
   |                ^
   |no implicit argument of type Blah.TC[([B] => Blah.Example1.Y[A, B])] was found for parameter tc of method toTcOps in object Blah.
   |I found:
   |
   |    tcX
   |
   |But value tcX in object Blah does not match type Blah.TC[([B] => Blah.Example1.Y[A, B])].
31 |      a.example                 // Error in 2.13 but ok in 2.12
   |      ^^^^^^^^^
   |      value example is not a member of Blah.Example2.Y[A, B].
   |      An extension method was tried, but could not be fully constructed:
   |
   |          Blah.toTcOps[([B] => Blah.Example2.Y[A, B]), A](a)(tcX)
32 |      toTcOps(a).example        // Error in 2.13 but ok in 2.12
   |                ^
   |no implicit argument of type Blah.TC[([B] => Blah.Example2.Y[A, B])] was found for parameter tc of method toTcOps in object Blah.
   |I found:
   |
   |    tcX
   |
   |But value tcX in object Blah does not match type Blah.TC[([B] => Blah.Example2.Y[A, B])].
```

**Comment by lrytz** [comment]
Let me trim the example (no type alias) and summarize the discussion. Given these definitions:

```
scala> trait Unary[A]
scala> trait Binary[A, B]
scala> trait BinaryExt[A, B] extends Unary[A]

scala> trait TC[F[_]]

scala> implicit val tcU: TC[Unary] = new TC[Unary]{}

scala> def foo[F[_], A](fa: F[A])(implicit tc: TC[F]) = 0
```

In plain 2.12 (without partial unification)
  - `foo(new Unary[Int]{})` infers to `foo[Unary, Int]`, and `tcU` is a matching implicit
  - `foo(new Binary[Int, String]{})` doesn't unify, the error message is `error: no type parameters for method foo: (fa: F[A])(implicit tc: TC[F])Int exist so that it can be applied to arguments (Binary[Int,String])`
  - `foo(new BinaryExt[Int, String]{})` infers to `foo[Unary, Int]`, and again `tcU` is a matching implicit

With partial unification (enabled by default in 2.13)
  - `foo(new Unary[Int]{})` is the same
  - `foo(new Binary[Int, String]{})` infers to `foo[[B]Binary[Int,B], String]`, then gives an error in implicit search `error: could not find implicit value for parameter tc: TC[[B]Binary[Int,B]]`
  - `foo(new BinaryExt[Int, String]{})` infers to `foo[[B]BinaryExt[Int,B], String]`, implicit search fails the same way

As @joroKr21 says, by the time the implicit search starts, the two type parameters of `foo` (`F` and `A`) are fixed. Changing this would be quite fundamental and I don't think it's possible in Scala 2. I'm not sure about Scala 3 (cc @smarter). 

Just for reference, in Scala 2.13:

```
scala> def f[T](x: T)(y: T) = x
f: [T](x: T)(y: T)T

scala> f("")(new Object)
             ^
       error: type mismatch;
        found   : Object
        required: String
```

Current dotty:

```
scala> def f[T](x: T)(y: T) = x
def f[T](x: T)(y: T): T

scala> f("")(new Object)
val res0: Object = ""
```

**Comment by smarter** [comment]
>  I'm not sure about Scala 3 (cc @smarter).

It's similar. Before doing an implicit search on a type, we instantiate all type variables that appear in that type and that have been constrained by a previous parameter (if we didn't, implicit search would fail with ambiguous implicits in many situations).

> Ok now I think I understand your other comment about feasibility & desirability. Sorry if this is naive, but wouldn't it just be a case of dealising and trying the implicit search again when it fails on a type alias?

In general, the compiler tries as much as possible to avoid backtracking, because it could easily blow-up compilation times.

**Comment by lrytz** [comment]
I think we have to close this as "works as intended" / "won't fix". @japgolly I hope the diagnosis in this ticket helps finding a way to work around this issue? Maybe by defining additional implicit instances?
