### ISSUE TITLE
2.13.0-M5 regression: Skinny ORM library fails to compile only with 2.13.0-M5

### ISSUE THREAD

**Issue by seratch** [scala/bug#11206]
Skinny ORM is a long-lived OSS library. I have been maintaining the library for years. The library has not been having any problems to compile with all Scala 2.13.0 milestone releases until M5. Only with M5 + ScalaTest 3.0.6-SNAP3, it fails to compile. I've not investigated if the issue is due to Scala lang or ScalaTest yet, though. I believe that Skinny ORM should compile without any problems. I haven't applied any changes to the library recently. Here is the evidence: https://travis-ci.org/skinny-framework/skinny-framework/builds/441636730

```
[info] Compiling 57 Scala sources to /home/travis/build/skinny-framework/skinny-framework/orm/target/scala-2.13.0-M5/test-classes ...
[error] /home/travis/build/skinny-framework/skinny-framework/orm/src/test/scala/blog/BlogSpec.scala:15:26: value createWithAttributes is not a member of object org.scalatest.Tag
[error]     val scalaTagId = Tag.createWithAttributes('name -> "Scala")
[error]                          ^
[error] /home/travis/build/skinny-framework/skinny-framework/orm/src/test/scala/blog/BlogSpec.scala:16:26: value createWithAttributes is not a member of object org.scalatest.Tag
[error]     val rubyTagId  = Tag.createWithAttributes('name -> "Ruby")
[error]                          ^
[error] /home/travis/build/skinny-framework/skinny-framework/orm/src/test/scala/blog/BlogSpec.scala:51:13: value createWithAttributes is not a member of object org.scalatest.Tag
[error]         Tag.createWithAttributes('name -> s"tag$i")
[error]             ^
[error] /home/travis/build/skinny-framework/skinny-framework/orm/src/test/scala/blog2/BlogSpec.scala:14:26: value createWithAttributes is not a member of object org.scalatest.Tag
[error]     val scalaTagId = Tag.createWithAttributes('name -> "Scala")
[error]                          ^
[error] /home/travis/build/skinny-framework/skinny-framework/orm/src/test/scala/blog2/BlogSpec.scala:15:26: value createWithAttributes is not a member of object org.scalatest.Tag
[error]     val rubyTagId  = Tag.createWithAttributes('name -> "Ruby")
[error]                          ^
```

references:

* https://github.com/skinny-framework/skinny-framework/pull/389
* https://travis-ci.org/skinny-framework/skinny-framework/builds/441636730

**Comment by SethTisue** [comment]
looks like a consequence of https://github.com/scala/scala/pull/6589 . we can reopen if you dig into it and find it's something else

**Comment by seratch** [comment]
@SethTisue Thank you for checking this. Can I expect that Scala lang team will ship another release including a fix for the problem soon?

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/6589 was a change made on purpose

I haven't looked at your codebase in detail, but you've either hit an intentional consequence or an unintentional consequence of https://github.com/scala/scala/pull/6589 . I'm guessing intentional consequence. there's nothing to fix unless you can demonstrate that the PR has bugs or unintended consequences

**Comment by seratch** [comment]
Okay, I understand. I've not tried yet, but it should be possible to make a minimal working example which reproduces the issue. With the simpler evidence, I'll reopen this or create another one. Thanks.
