### ISSUE TITLE
Compiler crash: "unexpected type representation reached the compiler backend"

### ISSUE THREAD

**Issue by gtyurtseven** [scala/bug#12511]
Hi,

When compiling  sbt project,  I got this following error :
```
[info] compiling 2 Scala sources to /home/gultugce/optimizationproject/target/scala-2.13/classes ...
[error] Error while emitting conjugategradient.scala
[error] <error> (of class scala.reflect.internal.Types$ErrorType$)
[warn] an unexpected type representation reached the compiler backend while compiling conjugategradient.scala: <error>. If possible, please file a bug on https://github.com/scala/bug/issues
[warn] one warning found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 12 s, completed Dec 8, 2021, 2:18:54 AM
```

My scala   version   is 2.13.7 . I already configured   build.sbt   as follows which compatible with  sbt  and scala versions. Working on ubuntu 20.04  environment.   Shall I choose    updating   scala or sbt version or   work on different environment to  eliminate this bug  I would really appreciate if you could suggest a solution.  
  
```
[info] compiling 2 Scala sources to /home/gultugce/optimizationproject/target/scala-2.13/classes ...
[error] Error while emitting conjugategradient.scala
[error] <error> (of class scala.reflect.internal.Types$ErrorType$)
[warn] an unexpected type representation reached the compiler backend while compiling conjugategradient.scala: <error>. If possible, please file a bug on https://github.com/scala/bug/issues
[warn] one warning found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 12 s, completed Dec 8, 2021, 2:18:54 AM
```

Here is  build.sbt file's content:

```
lazy val commonSettings = Seq(
  organization := "projectOptimization",
  scalaVersion := "2.13.7",
  version := "0.1.0-SNAPSHOT"
)

lazy val root = (project in file("."))
    .settings(
      commonSettings,
      name := "projectOptimization",
      libraryDependencies ++= Seq(
        "org.scalatest" %% "scalatest" % "3.2.10"  % "test",
        "com.typesafe" % "config" % "1.4.1",
        "commons-io" % "commons-io" % "2.4",
        "jline" % "jline" % "3.0.0.M1",
        "org.json4s" %% "json4s-native" % "4.0.3",
        "ch.qos.logback" % "logback-classic" % "1.3.0-alpha10" ,
        "com.typesafe.scala-logging" %%  "scala-logging" % "3.9.4",
        "org.scala-graph" %% "graph-core" % "1.13.3",
        "org.scalanlp" %% "breeze-natives" % "2.0",
        "org.scalanlp" %% "breeze-viz" % "2.0",
        "org.scalanlp" %% "breeze-macros" % "2.0",
        "org.jfree" % "jfreechart" % "1.5.1"
      )
    )

lazy val compiler = (project in file("conjugateGradient")).dependsOn(root)
    .settings(commonSettings:_*)

```

**Comment by SethTisue** [comment]
I don't think this is related to Scala or sbt version. Scala 2.13.7 is the latest, and the sbt version is unlikely to matter. (Though you should be using 1.5.5 if you can.)

apparently there's something in `conjugategradient.scala` that is giving the compiler trouble. are you able to reduce it to a minimized, self-contained, reproducible test case? that's what we'd need to make progress on whatever the underlying compiler bug is here.

**Comment by joroKr21** [comment]
Could you also check older Scala 2.13 versions so that we can determine if that's a regression?

**Comment by gtyurtseven** [comment]
import breeze.linalg.{CSCMatrix,DenseVector,norm}
import breeze.stats.distributions.{Gaussian, RandBasis, ThreadLocalRandomGenerator, Uniform}
import org.apache.commons.math3.random.{GaussianRandomGenerator,MersenneTwister}
import breeze.stats.distributions.{Gaussian,RandBasis}
import scala.util.Random
object conjugateGradient{
  def solvesparse(A:CSCMatrix[Double],b:DenseVector[Double],tolerance:Double=1e-10):DenseVector[Double]={
    val initialValue=DenseVector.zeros[Double](b.length)
    solvesparse3(A,b,tolerance,2*b.length)
    }

    def solvesparse3(A:CSCMatrix[Double],b:DenseVector[Double],tolerance:Double=1e-10,maxIter:Int):DenseVector[Double]={
      val initialValue=DenseVector.zeros[Double](b.length)
      solvesparse2(A,b,initialValue,tolerance,2*b.length,conjugateIterator)
      }


  def solvesparse2(A:CSCMatrix[Double],b:DenseVector[Double],xInit:DenseVector[Double],tolerance:Double=1e-10,maxIter:Int,func
    :(CSCMatrix[Double],DenseVector[Double],stateofConjugateGradient)=>stateofConjugateGradient):DenseVector[Double]={
    require(A.cols==b.length,"matrix and vector dimension disagreee")
    val initialValue=initialState(A,b,xInit)

    val solver=cgIterator(A,b,initialValue,func)
    print(solver)
    //if(norm(solver.y)>tolerance)
      //solver.x


}
 def  initialState(A:CSCMatrix[Double],b:DenseVector[Double],xInit:DenseVector[Double] ):Iterator[stateofConjugateGradient]={
   require(A.cols==b.length,"matrix and vector dimension disagreee")

   val solution=b-A*xInit
   val solution2=solution.copy
   Iterator(stateofConjugateGradient(xInit,solution,solution2))
  }


def  conjugateIterator(A:CSCMatrix[Double],b:DenseVector[Double],state:stateofConjugateGradient):stateofConjugateGradient={
   var  Aconj:DenseVector[Double]=A*state.x

   var rsq:Double=state.y.t*state.y
   val alpha:Double= rsq/state.x.t*Aconj
   val  xInit:DenseVector[Double]=state.x+alpha*state.x
   val rsq_next:DenseVector[Double]=state.y-alpha*state.y
   val beta:Double=rsq_next.t*rsq_next/rsq

    val pk=rsq_next+beta*state.x
   stateofConjugateGradient(xInit,rsq_next,pk)

 }

def cgIterator(A:CSCMatrix[Double],b:DenseVector[Double],initial:Iterator[stateofConjugateGradient],f:(CSCMatrix[Double],DenseVector[Double],stateofConjugateGradient)=>stateofConjugateGradient):stateofConjugateGradient={
  initial.foldLeft((initial.slice(0,1))){f(A,b,_)}


}

def cgIterator(A:CSCMatrix[Double],b:DenseVector[Double],initial:Iterator[stateofConjugateGradient],f:Iterable[(CSCMatrix[Double],DenseVector[Double],stateofConjugateGradient)=>stateofConjugateGradient]):Iterable[stateofConjugateGradient]={
   f.map(cgIterator(A,b,initial,_))
  }



  def randomDiagDomMatrix(n: Int, elementsPerColumn: Int): CSCMatrix[Double] = {
    val builder = new CSCMatrix.Builder[Double](n, n)
    // generate band
    for (col <- 0 until n; j <- 0 until elementsPerColumn) {
      val e = scala.util.Random.nextDouble()
      val row = scala.util.Random.nextInt()
      builder.add(row, col, e)
      builder.add(col, row, e)
    }
    // diagonally dominant
    for (i <- 0 until n) {
      builder.add(i, i, 2 * elementsPerColumn)
    }
    builder.result()
  }


  def main (args: Array[String]): Unit =
  {

    implicit val randBasis: RandBasis =
          new RandBasis(new ThreadLocalRandomGenerator(new MersenneTwister(234787)))

  val n_samples=300
  val n_features=500
  //val normalPdf=Gaussian(0.0, 1.0)
  val seed:Int=0
  //val randBasis: RandBasis = new RandBasis(new  GaussianRandomGenerator(new JDKRandomGenerator(seed)))
//  val normalPdf = new NormalDistribution(0.0,1.0)
    val MatrixA=CSCMatrix.rand(n_samples, n_features,Gaussian(0.0,1.0))
    val gaussianVector=DenseVector.rand(n_samples,Gaussian(0.0,1.0))

    solvesparse(MatrixA,gaussianVector, tolerance= 1e-10)

  }


case class stateofConjugateGradient(xInit:DenseVector[Double],y:DenseVector[Double],x:DenseVector[Double])


/*
object stateofConjugateGradient{

def apply(xInit:DenseVector[Double],y:DenseVector[Double],x:DenseVector[Double]):stateofConjugateGradient = new stateofConjugateGradient{stateofConjugateGradient(DenseVector(Array.empty[Double])  , DenseVector(Array.empty[Double]),DenseVector(Array.empty[Double])) }

}*/
}

**Comment by SethTisue** [comment]
what libraries would I need to have on my classpath in order to compile this?

**Comment by gtyurtseven** [comment]
A piece of code  which I worked   now   throws an error  as  stated  below.
home/gultugce/conjugategradient/src/main/scala/example/conjugateGradient.scala:54:21: type mismatch;
[error]  found   : List[conjugateGradient.stateofConjugateGradient]
[error]  required: conjugateGradient.stateofConjugateGradient
[error]   initial.toList.map(x=>f(A,b,x))
 Indeed , i  could not find a way  how  to initialize foldleft part . First I tried to initialize with empty constructor then tried to convert iterator to the list  to  initiate  the process inside of function  but neither of them works great.  I also  subsitute  foldleft with  map function to make it work.    
 could you check and   give a feedback about how to  correct this segment.

**Comment by gtyurtseven** [comment]
A piece of code  which I worked   now   throws an error  as  stated  below.
home/gultugce/conjugategradient/src/main/scala/example/conjugateGradient.scala:54:21: type mismatch;
[error]  found   : List[conjugateGradient.stateofConjugateGradient]
[error]  required: conjugateGradient.stateofConjugateGradient
[error]   initial.toList.map(x=>f(A,b,x))
 Indeed , i  could not find a way  how  to initialize foldleft part . First I tried to initialize with empty constructor then tried to convert iterator to the list  to  initiate  the process inside of function  but neither of them works great.  I also  subsitute  foldleft with  map function to make it work.    
 could you check and   give a feedback about how to  correct this segment.

**Comment by SethTisue** [comment]
@gtyurtseven this is the Scala bug tracker — our primary goal here is to try to isolate and, if possible, fix bugs in Scala itself.

if you want help with your code, try https://user.scala-lang.org (or see https://www.scala-lang.org/community/ for other suggestions of where to ask questions)

**Comment by gtyurtseven** [comment]
ok thanks..

**Comment by SethTisue** [comment]
https://stackoverflow.com/questions/70368345/initialization-foldeft-function-in-scala-with-iterator-of-class-object

**Comment by SethTisue** [comment]
I'm closing the ticket since we don't have enough information to know if this is distinct from any other "unexpected type representation reached the compiler backend" ticket
