### ISSUE TITLE
Confusion between named parameter and an unrelated val

### ISSUE THREAD

**Issue by kmltml** [scala/bug#10336]
Trying the following in scala repl:
```scala
case class C(a: Int = 10, b: String = "20")
def c(c: C): (Int, String) = (c.a, c.b)
val (x, y) = c(C(b = "30"))
val a = y.toInt
```
gives the following error:
```
<console>:13: error: recursive value x$1 needs type
       val (x, y) = c(C(b = "30"))
               ^
<console>:13: warning: failed to determine if 'a = ...' is a named argument or an assignment expression.
an explicit type is required for the definition mentioned in the error message above.
       val (x, y) = c(C(b = "30"))
```
Changing the val's name to anything else makes the problem disappear

**Comment by som-snytt** [comment]
The `x$1` is the tmp var for the RHS of the multi assignment.

A guess via gitter: That's a wild one. It looks like it tries to use default arg for the a param, then complains that your val a doesn't have an explicit type. (val a: Int fixes that.) But if the compiler is supplying a default arg, obviously it knows that the expression is not an assignment.

**Comment by McBrainy** [comment]
I just ran into something similar. Here's my minimal example:

```scala
{ // Doesn't happen outside of code block
  val a = A(B(5), 4).copy(c = 0) // Can be a different value being changed
                                 // Doesn't happen for no-arg copy invocation
  val b = B(a.b.n) // Doesn't happen unless val is named "b" or "c"
  //val b = a2.b.copy(n = 0) // This line also triggers it
  // It even happens if I assign a.b to a temp variable
}

case class A(b: B, c: Int)
case class B(n: Int)
```

And the compiler output:

```
[redacted]/test.scala:4: error: recursive value a needs type
  val b = B(a.b.n) // Doesn't happen unless val is named "b" or "c"
            ^
[redacted]/test.scala:2: warning: failed to determine if 'b = ...' is a named argument or an assignment expression.
an explicit type is required for the definition mentioned in the error message above.
  val a = A(B(5), 4).copy(c = 0) // Can be a different value being changed
                     ^
one warning found
one error found
```

Explicitly typing `b` is a fine workaround.

**Comment by melezov** [comment]
It seems this bug has been around since Scala v2.0.0:

    class Foo(val bar: String)
    class Bar {{
      val foo = new Foo(bar = "dinamo")
      val bar = foo.bar;
      bar
    }}

When compiling said snippet with Scala from 2005:

    foo.scala:4 error: recursive value foo needs type
      val bar = foo.bar;
                ^
    one error found

There's a ton of different cases which may trigger it, but it's always related to usage of a conflicting variable name with a named parameter. What's worse is that when you are compiling it via SBT/scalac as of 2.12.3 it does **not** give you the hint that it's confused but just keeps ranting about the _recursive value a needs type_.

+1

**Comment by som-snytt** [comment]
@melezov That's the normal case for the error message, except possibly it could notice that it can't be an assignment. In 2.12.4, `-Xsource:2.13` lets your example compile.

**Comment by lrytz** [comment]
Closing this; as mentioned by @som-snytt, all the examples are fixed in 2.13 (2.12.4 + `-Xsource:2.13`), https://github.com/scala/scala/pull/6089.

**Comment by som-snytt** [comment]
Coincidentally, I just hit this on a Friday afternoon just trying to get something done quickly and instead spent an hour in brain fog.

```
object Main extends App {
  case class Args(version: Int = 42, name: String = "fred")

  val argr = "--(?<name>.*)=(?<value>.*)".r

  val config = args.foldLeft(Args())((args, arg) => arg match {
    case argr(name, value) =>
      name match {
        case "version" => args.copy(version = value.toInt)
        case "name"    => args.copy(name = value)
      }
  })

  def version = config.version
}

```
results in
```
tricky.scala:10: error: not found: value value
        case "version" => args.copy(version = value.toInt)
                                              ^
tricky.scala:11: error: value copy is not a member of Array[String]
        case "name"    => args.copy(name = value)
                               ^
tricky.scala:11: error: not found: value name
        case "name"    => args.copy(name = value)
                                    ^
tricky.scala:10: warning: failed to determine if 'version = ...' is a named argument or an assignment expression.
an explicit type is required for the definition mentioned in the error message above.
        case "version" => args.copy(version = value.toInt)
                                            ^
one warning found
three errors found

```
Moreover, this version works, which is what I started with ninety minutes ago:
```
object Main extends App {
  case class Args(version: Int = 42, name: String = "fred")

  val argr = "--(?<name>.*)=(?<value>.*)".r

  def addArg(args: Args, arg: String): Args = arg match {
    case argr(name, value) =>
      name match {
        case "version" => args.copy(version = value.toInt)
        case "name"    => args.copy(name = value)
      }
  }

  val config = args.foldLeft(Args())((args, arg) => addArg(args, arg))

  def version = config.version
}

```
But I actually saw this broken namer first:
```
import X._

object Main extends App {
  case class Args(version: Int = 42, name: String = "fred")

  val argr = "--(?<name>.*)=(?<value>.*)".r

  val config = args.foldLeft(Args())((args, arg) => arg match {
    case argr(name, value) =>
      name match {
        case "version" => args.copy(version = value.toInt)
        case "name"    => args.copy(name = value)
      }
  })

  def version = config.version
}

object X extends Enumeration {
  val A, B, C = Value
}

```
So the compiler starts out with some friendly advice, which seemed so plausible that you don't even stop to wonder why the compiler has that odd smile on its face.
```
tricky.scala:2: error: encountered unrecoverable cycle resolving import.
Note: this is often due in part to a class depending on a definition nested within its companion.
If applicable, you may wish to try moving some members into another object.
import X._
       ^
tricky.scala:24: error: not found: value value
        case "version" => args.copy(version = value.toInt)
                                              ^
tricky.scala:25: error: value copy is not a member of Array[String]
        case "name"    => args.copy(name = value)
                               ^
tricky.scala:25: error: not found: value name
        case "name"    => args.copy(name = value)
                                    ^
tricky.scala:24: warning: failed to determine if 'version = ...' is a named argument or an assignment expression.
an explicit type is required for the definition mentioned in the error message above.
        case "version" => args.copy(version = value.toInt)
                                            ^
one warning found
four errors found

```

**Comment by DavidPerezIngeniero** [comment]
I have simple code that used to compile in 2.12.4 and now gives this error in 2.12.7.
I'll try later to provide a simple example.
