### ISSUE TITLE
Mixin trait using abstract member of parent class won't compile when they reside in different packages

### ISSUE THREAD

**Issue by Naitreey** [scala/bug#12249]
The bug was firstly asked on stackoverflow. [Here is the reference post](https://stackoverflow.com/q/64999145/1602266). [Here's a gist to reproduce the issue](https://gist.github.com/DmytroMitin/f1432fd919efd975a1151c545d71af33), created by @DmytroMitin.
Tested on Scala 2.12.11, 2.13.3, 2.13.4.

## reproduction steps

1. In file `A.scala`, we have
   ```scala
   package mixintest.a
   abstract class A {
     protected val x: Int
   }
   ```
2. In file `B.scala`, we have
   ```scala
   package mixintest.b
   import mixintest.a.A
   trait B extends A {
     println(x)
   }
   ```
3. In file `C.scala`, we have
   ```scala
   package mixintest.c
   import mixintest.a.A
   import mixintest.b.B
   case class C(override protected val x: Int) extends A with B
   ```
4. `build.sbt`
   ```scala
   ThisBuild / scalaVersion := "2.13.3"
   ```

5. run `compile` in sbt shell, emitting the following error:
```
sbt:scala> compile
[info] Compiling 3 Scala sources to /Users/naitree/Documents/try/scala/target/scala-2.13/classes ...
[error] /Users/naitree/Documents/try/scala/src/main/scala/C.scala:4:12: Member value x of mixin trait B is missing a concrete super implementation.
[error] case class C(override protected val x: Int) extends A with B
[error]            ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed Nov 26, 2020, 5:13:32 PM
sbt:scala>
```

## problem

When `A`, `B`, `C` are defined in the same package, it compiles successfully. But it won't compile if they reside in different packages.

By the way, I can workaround the bug, by re-declaring the abstrat member in `B` trait:
```scala
package mixintest.b
import mixintest.a.A
trait B extends A {
  protected val x: Int  // workaround
  println(x)
}
```

**Comment by obones** [comment]
Hello,

I'm facing a very similar issue with a code that worked in Scala 2.11 and that is extending a `org.apache.spark.Partition` in my own package like this:

```scala
private[mypackage] class MyRDDPartition(
  override val index: Int, val firstRow: Long, val lastRow: Long) extends Partition
```

The error message is this:

```
Member method equals of mixin trait Partition is missing a concrete super implementation in class MyRDDPartition
```

I have tried overriding `equals` in my class definition, or add `with Serializable` after `extends Partition` but it did not change anything.

What can I do here?
Is there a workaround that I can apply?

**Comment by obones** [comment]
Well, as it turns out, there is, with the use of a bridge class placed in the package where the `Partition` class belongs:

```scala
package org.apache.spark

import org.apache.spark.Partition

class MyRDDPartition(
  override val index: Int, val firstRow: Long, val lastRow: Long) extends Partition  {
}

class PartitionBridge(index: Int, firstRow: Long, lastRow: Long) {

  val myFileRDDPartition = new MyFileRDDPartition(index, firstRow, lastRow)

}
```

Then when it's time to build a `MyFileRDDPartition` instance in code, you use `new PartitionBridge(index, firstRow, lastRow).myFileRDDPartition` instead of the previous code.
Not pretty, but at least it works.

**Comment by lrytz** [comment]
The orginally reported example seems fixed since 2.13.7.

@obones what Scala version were you using with spark?

**Comment by obones** [comment]
> @obones what Scala version were you using with spark?

At the time I wrote this, it was 2.13.2 but now that I have moved to 2.13.11 you are right, the bridge is no longer required
