### ISSUE TITLE
Symbol `X` is missing from the classpath

### ISSUE THREAD

**Issue by izhangzhihao** [scala/bug#10306]
Use sbt create two project,
the first one named `apackage`
```scala
package missingsymbol {

  package object p  {
    type Container = String
  }

}


package missingsymbol.p {
  class Test extends Container.Nested

  object Container {
    trait Nested
  }
}
```

the second one named `use`

```scala
package use
object use {
  val error = new missingsymbol.p.Test
}
```

scala version is 2.11.11, I got 

```
[error] ScalaIssues#10306/use/src/main/scala/use/use.scala:4: Symbol 'type missingsymbol.p.Container.Nested' is missing from the classpath.
[error] This symbol is required by 'class missingsymbol.p.Test'.
[error] Make sure that type Nested is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Test.class' was compiled against an incompatible version of missingsymbol.p.Container.
[error]   val error = new missingsymbol.p.Test
[error]                   ^
[error] one error found
[error] (use/compile:compileIncremental) Compilation failed
```

**Comment by izhangzhihao** [comment]
see https://github.com/izhangzhihao/ScalaIssues-10306

**Comment by SethTisue** [comment]
this is misuse of sbt, not a Scala bug. you're mixing Scala versions — one of your projects is Scala 2.10, the other is 2.11

**Comment by SethTisue** [comment]
is this reproducible outside of sbt? if so, how? in order for this to be a valid bug in this tracker, we would need to know that sbt doesn't need to be in the picture

**Comment by dwijnand** [comment]
I can't reproduce it with scalac. But I can reproduce it with sbt 0.13.15 and sbt 1.0.0-M5.

**Comment by izhangzhihao** [comment]
In scala 2.12.2，it works fine

**Comment by SethTisue** [comment]
great then!

**Comment by retronym** [comment]
FTR This appears to have been a Scalac bug that was fixed somewhere between v2.12.0 and v2.12.1. My guess would be https://github.com/scala/scala/pull/5482, although I haven't bisected to verify.
