### ISSUE TITLE
NoSuchMethodError $adapted

### ISSUE THREAD

**Issue by scabug** [scala/bug#10054]
I have a macro that generates code based on a list of anonymous functions:
https://github.com/backuity/matchete/blob/master/macros/src/main/scala/org/backuity/matchete/Diffable.scala#L97

When using it:
https://github.com/backuity/matchete/blob/master/core/src/test/scala/org/backuity/matchete/SeqDiffableTest.scala#L28

I get a `NoSuchMethodError` exception for `org.backuity.matchete.SeqDiffableTest.$anonfun$beEqualNestedList_Error$3$adapted(Lorg/backuity/matchete/TestUtil$Stuff;)Ljava/lang/Object;`
This can be seen in the following build:
https://travis-ci.org/backuity/matchete/builds/175086474

This code worked with 2.11.8.

It seems to me that the `Diffable` instance created by the macro is unable to call one of the anonymous function.

**Comment by som-snytt** [comment]
As mentioned on the linked ticket, which has a simple example, delambdafy rewrites the call site and adds an adapter, which will correctly go on an anon class to which a lambda has been moved, while lambda bodies remain incorrectly on the original class, because the macro isn't quite hygienic in its rewrite. I guess the workaround suggested here is what I suggested, don't move the lambda?
